=== regione-marche/org.seda.payer.manager.web/WebContent/WEB-INF/xsd/maf-actions.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
targetNamespace="http://action.core.maf.j2ee5.seda.com"
xmlns="http://action.core.maf.j2ee5.seda.com"
elementFormDefault="qualified">
 
<xsd:annotation>
 	<xsd:documentation xml:lang="en">
    </xsd:documentation>
</xsd:annotation>

<xsd:element name="actions-mapping" type="actionsMappingType"/>
  
<xsd:complexType name="actionsMappingType">
	<xsd:sequence>
		<xsd:element name="menu" type="menuType" minOccurs="0" maxOccurs="1"/>
		<xsd:element name="complex-actions" type="complexType" minOccurs="0" maxOccurs="1"/>
		<xsd:element name="global-ruleset" type="globalRulesetType" minOccurs="0" maxOccurs="1"/>
		<xsd:element name="action" type="actionType" minOccurs="0" maxOccurs="unbounded"/>
    </xsd:sequence>
</xsd:complexType>

<xsd:complexType name="menuType">
	<xsd:sequence>
		<xsd:element name="link" type="menuLinkType" minOccurs="1" maxOccurs="unbounded"/>	
    </xsd:sequence>    
</xsd:complexType>

<xsd:complexType name="menuLinkType">
	<xsd:attribute name="text" type="xsd:string" use="required"/>	
	<xsd:attribute name="actionurl" type="xsd:string" use="required"/>
	<xsd:attribute name="enabled" type="xsd:boolean" use="optional"/>
</xsd:complexType>

<xsd:complexType name="complexType">
	<xsd:sequence>
		<xsd:element name="complex-target" type="complexTargetType" minOccurs="1" maxOccurs="unbounded"/>	
    </xsd:sequence>    
</xsd:complexType>

<xsd:complexType name="complexTargetType">
	<xsd:attribute name="value" type="xsd:string" use="required"/>	
	<xsd:attribute name="actionurl" type="xsd:string" use="required"/>
</xsd:complexType>

<xsd:complexType name="globalRulesetType">
	<xsd:sequence>
		<xsd:element name="regexset" type="regexsetType" minOccurs="0" maxOccurs="unbounded"/>	
		<xsd:element name="ruleset" type="rulesetType" minOccurs="0" maxOccurs="unbounded"/>
    </xsd:sequence>
</xsd:complexType>

<xsd:complexType name="regexsetType">
	<xsd:sequence>
		<xsd:element name="regex" type="regexType" minOccurs="1" maxOccurs="unbounded"/>
	</xsd:sequence>
</xsd:complexType>

<xsd:complexType name="regexType">
	<xsd:sequence>
		<xsd:element name="pattern" type="xsd:string" minOccurs="1" maxOccurs="1"/>
		<xsd:element name="description" type="xsd:string" minOccurs="1" maxOccurs="1"/>
	</xsd:sequence>
	<xsd:attribute name="name" type="xsd:string" use="required"/>	
</xsd:complexType>

<xsd:complexType name="rulesetType">
	<xsd:sequence>
		<xsd:element name="rule" type="ruleType" minOccurs="0" maxOccurs="unbounded"/>
	</xsd:sequence>
</xsd:complexType>

<xsd:complexType name="ruleType">
	<xsd:sequence>
		<xsd:element name="validation" type="xsd:string" minOccurs="0" maxOccurs="1"/>
		<xsd:element name="missing" type="ruleCategoryType" minOccurs="1" maxOccurs="1"/>
		<xsd:element name="malformed" type="ruleCategoryType" minOccurs="1" maxOccurs="1"/>
	</xsd:sequence>
	<xsd:attribute name="name" type="xsd:string" use="required"/>
	<xsd:attribute name="regex" type="xsd:string"/>
</xsd:complexType>

<xsd:complexType name="ruleCategoryType">
	<xsd:sequence>
		<xsd:element name="rule-action" type="ruleActionType" minOccurs="0" maxOccurs="unbounded"/>
	</xsd:sequence>
	<xsd:attribute name="severity" use="required">
		<xsd:simpleType>
			<xsd:restriction base="xsd:string">
				<!-- xsd:enumeration value="ignore"/ -->
				<xsd:enumeration value="continue"/>				
				<xsd:enumeration value="fatal"/>
			</xsd:restriction>
		</xsd:simpleType>
	</xsd:attribute>
</xsd:complexType>

<xsd:complexType name="ruleActionType">
	<xsd:sequence>
		<xsd:element name="parameter" type="ruleActionParameterType" minOccurs="0" maxOccurs="unbounded"/>
	</xsd:sequence>
	<xsd:attribute name="class" use="required"/>
</xsd:complexType>

<xsd:complexType name="ruleActionParameterType">
	<xsd:attribute  name="name" type="xsd:string" use="required"/>
	<xsd:attribute  name="value" type="xsd:string" use="required"/>
</xsd:complexType>

<xsd:complexType name="actionType">
	<xsd:sequence>
		<xsd:element name="role-collection" type="actionRoleType" minOccurs="0" maxOccurs="1"/>
		<xsd:element name="description" type="xsd:string" minOccurs="0" maxOccurs="1"/>			
		<xsd:element name="action-class" type="xsd:string"/>
		<xsd:element name="flow" type="flowType" minOccurs="0" maxOccurs="1"/>
		<xsd:element name="writer" type="writerType" minOccurs="0" maxOccurs="1"/>
		<xsd:element name="redirect" type="redirectType" minOccurs="0" maxOccurs="1"/>
		<xsd:element name="settings" type="settingsType" minOccurs="0" maxOccurs="1"/>				
		<xsd:element name="ruleset" type="rulesetType" minOccurs="0" maxOccurs="1"/>		
    </xsd:sequence>
    <xsd:attribute name="url" type="xsd:string" use="required"/>
    <xsd:attribute name="menuaction" type="xsd:string"/>    
    <xsd:attribute name="screen" type="xsd:string" />
    <xsd:attribute name="flow" type="xsd:boolean" />    
    <xsd:attribute name="writer" type="xsd:boolean" />    
    <xsd:attribute name="redirect" type="xsd:boolean" />    
    <xsd:attribute name="csrf" type="xsd:boolean" />    
</xsd:complexType>

<xsd:complexType name="actionRoleType">
	<xsd:sequence>
		<xsd:element name="role" type="xsd:string" minOccurs="1" maxOccurs="unbounded"/>	
    </xsd:sequence>    	
</xsd:complexType>

<xsd:complexType name="flowType">
	<xsd:sequence>
		<xsd:element name="settings" type="settingsType" minOccurs="0" maxOccurs="1"/>
		<xsd:element name="properties" type="propertiesType" minOccurs="0" maxOccurs="1"/>	
		<xsd:element name="result" type="resultType" minOccurs="1" maxOccurs="unbounded"/>
    </xsd:sequence>
    <xsd:attribute name="class" type="xsd:string" use="required"/>
</xsd:complexType>

<xsd:complexType name="resultType">
    <xsd:attribute name="value" type="xsd:string" use="required"/>
    <xsd:attribute name="screen" type="xsd:string"/>
    <xsd:attribute name="applid" type="xsd:string"/>
    <xsd:attribute name="writer" type="xsd:string"/>    
    <xsd:attribute name="redirect" type="xsd:string"/>
    <xsd:attribute name="inScope" type="xsd:boolean"/>
	<xsd:attribute name="content-type" type="xsd:string"/>    
	<xsd:attribute name="attach" type="xsd:string"/>
</xsd:complexType>

<xsd:complexType name="writerType">
    <xsd:attribute name="id" type="xsd:string" use="required"/>
	<xsd:attribute name="attach" type="xsd:string"/>    
	<xsd:attribute name="scope">
		<xsd:simpleType>
			<xsd:restriction base="xsd:string">
				<xsd:enumeration value="application"/>
				<xsd:enumeration value="session"/>				
				<xsd:enumeration value="request"/>
			</xsd:restriction>
		</xsd:simpleType>
	</xsd:attribute>
	<xsd:attribute name="inScope" type="xsd:boolean"/>
	<xsd:attribute name="content-type" type="xsd:string" use="required"/>
</xsd:complexType>

<xsd:complexType name="redirectType">
    <xsd:attribute name="id" type="xsd:string"/>
	<xsd:attribute name="url" type="xsd:string"/>    
</xsd:complexType>  

<xsd:complexType name="settingsType">
	<xsd:sequence>
		<xsd:element name="property" type="propertyType" minOccurs="1" maxOccurs="unbounded"/>
    </xsd:sequence>    
</xsd:complexType>

<xsd:complexType name="propertiesType">
	<xsd:sequence>
		<xsd:element name="property" type="propertyType" minOccurs="1" maxOccurs="unbounded"/>
    </xsd:sequence>    
</xsd:complexType>    

<xsd:complexType name="propertyType">
    <xsd:attribute name="key" type="xsd:string" use="required"/>
	<xsd:attribute name="value" type="xsd:string" use="required"/>    
</xsd:complexType>  
  
</xsd:schema>

=== regione-marche/org.seda.payer.manager.web/WebContent/applications/payer/riversamento/maf-actions.xml
<?xml version="1.0" encoding="UTF-8"?>

<actions-mapping xmlns="http://action.core.maf.j2ee5.seda.com"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://action.core.maf.j2ee5.seda.com ../../../WEB-INF/xsd/maf-actions.xsd">

	<global-ruleset>
 		<regexset>
 			<regex name="numcell_regex">
 				<pattern>^\d{1,20}$</pattern>
 				<description>digits</description>
 			</regex>
 			<regex name="email_regex">
 				<pattern><![CDATA[^[\w\-\+\&\*]+(?:\.[\w\-\_\+\&\*]+)*@(?:[a-zA-Z0-9\-]+\.)+[a-zA-Z]{2,7}$]]></pattern>
 				<description></description>
 			</regex> 
 			<regex name="codice18char_regex">
 				<pattern>^\w{1,18}$</pattern>
 				<description></description>
 			</regex>
 			<regex name="num3_regex">
 				<pattern>^\d{1,3}$</pattern>
 				<description>digits</description>
 			</regex>
 			<regex name="num15_regex">
 				<pattern>^\d{1,15}$</pattern>
 				<description>digits</description>
 			</regex>
 			<regex name="ip_regex">
 				<pattern>^\b(?:\d{1,3}\.){3}\d{1,3}\b$</pattern>
 				<description>ip</description>
 			</regex>
 			<regex name="descrizione64_regex">
 				<pattern>^[\w\t \?+().,;'* \$ % @ = -]{0,64}$</pattern>
 				<description></description>
 			</regex>
 		</regexset>
 	</global-ruleset>


<!-- SEZIONE RIVERSAMENTI 2.1 -->

    <action url="ricercaRiversamenti.do" screen="ricercaRiversamenti.screen" flow="true">
       <role-collection>
			<role>AMMI</role>
			<role>AMEN</role>
			<role>AMSO</role>
			<role>AMUT</role>
		</role-collection>
        <action-class>org.seda.payer.manager.riversamento.actions.RicercaRiversamentiAction</action-class>
        <flow class="org.seda.payer.manager.riversamento.flows.RicercaRiversamentiFlow">
           	<result value="ricerca" screen="ricercaRiversamenti.screen" />
           	<result value="alertRiv" screen="alertRiversamenti.screen" />
        </flow>

    </action>

    <action url="riversamentiDettaglioImp.do" screen="riversamentiDettaglioImp.screen" flow="false">
       <role-collection>
			<role>AMMI</role>
			<role>AMSO</role>
			<role>AMUT</role>
		</role-collection>
        <action-class>org.seda.payer.manager.riversamento.actions.RicercaRiversamentiDettImpAction</action-class>
    </action>

    <action url="riversamentiDettaglioContr.do" screen="riversamentiDettaglioContr.screen" flow="false">
       <role-collection>
			<role>AMMI</role>
			<role>AMEN</role>
			<role>AMSO</role>
			<role>AMUT</role>
		</role-collection>
        <action-class>org.seda.payer.manager.riversamento.actions.RicercaRiversamentiDettContrAction</action-class>
    </action>

<!-- ACTION SOSPENSIONE -->

    <action url="riversamentiSospensioneStart.do" screen="riversamentiSospensione.screen" flow="false">
       <role-collection>
			<role>AMMI</role>
			<role>AMSO</role>
			<role>AMUT</role>
		</role-collection>
        <action-class>org.seda.payer.manager.riversamento.actions.SospensioneRivAction</action-class>
    </action>


<!-- ACTION CAMBIO STATO -->

    <!--   action url="aggiornaStatoRiv.do" screen="ricercaRiversamenti.screen" flow="false" -->
    <action url="aggiornaStatoRiv.do" flow="true">
       <role-collection>
			<role>AMMI</role>
			<role>AMSO</role>
			<role>AMUT</role>
		</role-collection>
    	<action-class>org.seda.payer.manager.riversamento.actions.AggiornaStatoAction</action-class>
        <flow class="org.seda.payer.manager.riversamento.flows.AggiornaStatoFlow">
           	<result value="ricerca" screen="ricercaRiversamenti.do" />
           	<result value="alertRiv" screen="alertRiversamento.screen" />
        </flow>
    </action>

<!-- ACTION AGGIORNA FLAG CBI -->

    <action url="aggiornaFlagCBI.do" flow="true">
       <role-collection>
			<role>AMMI</role>
			<role>AMSO</role>
			<role>AMUT</role>
		</role-collection>
    	<action-class>org.seda.payer.manager.riversamento.actions.AggiornaFlagCBIAction</action-class>
        <flow class="org.seda.payer.manager.riversamento.flows.AggiornaStatoFlow">
           	<result value="ricerca" screen="ricercaRiversamenti.do" />
           	<result value="alertRiv" screen="alertRiversamento.screen" />
        </flow>
    </action>

<!-- ACTION DOWNLOAD FLUSSO CBI -->
    <action url="downloadFlussoCBI.do" writer="true">
       <role-collection>
			<role>AMMI</role>
			<role>AMEN</role>
			<role>AMSO</role>
			<role>AMUT</role>
		</role-collection>
        <action-class>org.seda.payer.manager.riversamento.actions.DownloadFlussoCBIAction</action-class>
		<writer id="CBIRiv" content-type="application/txt" inScope="false" attach="CBIRivD"/>
    </action>

<!-- ACTION DOWNLOAD PDF -->
    <action url="stampaPDFRiv.do" writer="true">
       <role-collection>
			<role>AMMI</role>
			<role>AMEN</role>
			<role>AMSO</role>
			<role>AMUT</role>
		</role-collection>
        <action-class>org.seda.payer.manager.riversamento.actions.StampaPDFRivAction</action-class>
		<writer id="pdfRiv" content-type="application/pdf" inScope="false" attach="pdfRivD"/>
    </action>

<!-- ACTION DOWNLOAD CSV -->
    <action url="stampaCSVRiv.do" writer="true">
       <role-collection>
			<role>AMMI</role>
			<role>AMEN</role>
			<role>AMSO</role>
			<role>AMUT</role>
		</role-collection>
        <action-class>org.seda.payer.manager.riversamento.actions.StampaCSVRivAction</action-class>
		<writer id="csvRiv" content-type="application/txt" inScope="false" attach="csvRivD"/>
    </action>

</actions-mapping>

=== regione-marche/org.seda.payer.manager.web/WebContent/applications/payer/eccedenze/maf-actions.xml
<?xml version="1.0" encoding="UTF-8"?>

<actions-mapping xmlns="http://action.core.maf.j2ee5.seda.com"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://action.core.maf.j2ee5.seda.com ../../../WEB-INF/xsd/maf-actions.xsd">

	<global-ruleset>
 		<regexset>
 			<regex name="numcell_regex">
 				<pattern>^\d{1,20}$</pattern>
 				<description>digits</description>
 			</regex>
 			<regex name="email_regex">
 				<pattern><![CDATA[^[\w\-\+\&\*]+(?:\.[\w\-\_\+\&\*]+)*@(?:[a-zA-Z0-9\-]+\.)+[a-zA-Z]{2,7}$]]></pattern>
 				<description></description>
 			</regex> 
 			<regex name="codice18char_regex">
 				<pattern>^\w{1,18}$</pattern>
 				<description></description>
 			</regex>
 			<regex name="num3_regex">
 				<pattern>^\d{1,3}$</pattern>
 				<description>digits</description>
 			</regex>
 			<regex name="num15_regex">
 				<pattern>^\d{1,15}$</pattern>
 				<description>digits</description>
 			</regex>
 			<regex name="ip_regex">
 				<pattern>^\b(?:\d{1,3}\.){3}\d{1,3}\b$</pattern>
 				<description>ip</description>
 			</regex>
 			<regex name="descrizione64_regex">
 				<pattern>^[\w\t \?+().,;'* \$ % @ = -]{0,64}$</pattern>
 				<description></description>
 			</regex>
 		</regexset>
 	</global-ruleset>


<!-- SEZIONE ECCEDENZE -->

    <action url="ricercaEccedenze.do" screen="ricercaEccedenze.screen" flow="false">
       <role-collection>
			<role>AMMI</role>
			<role>AMEN</role>
			<role>AMSO</role>
			<role>AMUT</role>
		</role-collection>
        <action-class>org.seda.payer.manager.eccedenze.actions.RicercaEccedenzeAction</action-class>
    </action>

    <action url="eccedenzeDettaglio.do" screen="eccedenzeDettaglio.screen" flow="false">
       <role-collection>
			<role>AMMI</role>
			<role>AMSO</role>
			<role>AMUT</role>
		</role-collection>
        <action-class>org.seda.payer.manager.eccedenze.actions.RicercaEccedenzeDettAction</action-class>
    </action>

</actions-mapping>

=== regione-marche/org.seda.payer.manager.web/WebContent/applications/payer/monitoraggiocup/maf-actions.xml
<?xml version="1.0" encoding="UTF-8"?>

<actions-mapping xmlns="http://action.core.maf.j2ee5.seda.com"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://action.core.maf.j2ee5.seda.com ../../../WEB-INF/xsd/maf-actions.xsd">
	
	<global-ruleset>
 		<regexset>
 			<regex name="descrizione64_regex">
 				<pattern>^(?:(?!').)*{0,64}$</pattern>
 				<description></description>
 			</regex>
 		</regexset>
 	</global-ruleset>
    
    <action url="monitoraggiocup.do" screen="monitoraggiocup.screen">
        <action-class>org.seda.payer.manager.monitoraggiocup.actions.MonitoraggioCupAction</action-class>
		<ruleset>
        	<rule name="txtIdTransazione" regex="descrizione64_regex">
        		<missing severity="continue"/>
        		<malformed severity="fatal"/>
        	</rule>  
        	<rule name="txtNumeroDocumento">
        		<validation>maxlength=128</validation>
        		<missing severity="continue"/>
        		<malformed severity="fatal"/>
        	</rule>  
        	<rule name="txtNumeroOperazione">
        		<validation>maxlength=128</validation>
        		<missing severity="continue"/>
        		<malformed severity="fatal"/>
        	</rule>  
        </ruleset> 
    </action>
    
    <action url="downloadXml.do" writer="true">
    	<action-class>org.seda.payer.manager.monitoraggiocup.actions.DownloadXmlAction</action-class>
    	<writer id="file_xml" content-type="plain/txt" inScope="true" attach="nome_file_xml"/>
    </action>

	<action url="dettaglioNotifica.do" screen="monitoraggiocupdettaglio.screen">
		<action-class>org.seda.payer.manager.monitoraggiocup.actions.MonitoraggioCupDettaglioAction</action-class>
	</action>
	
	<action url="ritorna.do" screen="monitoraggiocup.do">
		<description>Action per la gestione del ritorno ad altro screen con viewstate</description>
        <action-class>org.seda.payer.manager.monitoraggiocup.actions.RitornaAction</action-class>
    </action>  
    
    <action url="notifica.do" flow="true">
        <action-class>org.seda.payer.manager.monitoraggiocup.actions.NotificaAction</action-class>
        <flow class="org.seda.payer.manager.monitoraggiocup.flows.MonitoraggioCupNotificaFlow">
        	<result value="monitoraggiocup" screen="monitoraggiocup.screen"/>
        	<result value="monitoraggiocupdettaglio" screen="monitoraggiocupdettaglio.screen"/>
        </flow>
    </action> 

</actions-mapping>

=== regione-marche/org.seda.payer.manager.web/WebContent/applications/payer/riconciliazione/maf-actions.xml
<?xml version="1.0" encoding="UTF-8"?>

<actions-mapping xmlns="http://action.core.maf.j2ee5.seda.com"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://action.core.maf.j2ee5.seda.com ../../../WEB-INF/xsd/maf-actions.xsd">

	<global-ruleset>
 		<regexset>
 			<regex name="codice5char_regex">
 				<pattern>^\w{1,5}|\s{1,5}$</pattern>
 				<description></description>
 			</regex>
 			<regex name="codice12char_regex">
 				<pattern>^\w{1,12}|\s{1,12}$</pattern>
 				<description></description>
 			</regex>
 			<regex name="codice16char_regex">
 				<pattern>^\w{1,16}$</pattern>
 				<description></description>
 			</regex>
 			<regex name="codice20char_regex">
 				<pattern>^\w{1,20}$</pattern>
 				<description></description>
 			</regex>
 			<regex name="num15_regex">
 				<pattern>^\d{1,15}$</pattern>
 				<description>digits</description>
 			</regex>
 			<regex name="descrizione20_regex">
 				<pattern>^[\w\t \?+().,;'* \$ % @ = -]{0,20}$</pattern>
 				<description></description>
 			</regex>
 			<regex name="descrizione64_regex">
 				<pattern>^[\w\t \?+().,;'* \$ % @ = -]{0,64}$</pattern>
 				<description></description>
 			</regex>
 		</regexset>
 	</global-ruleset>

    <action url="riconciliazioneTransazioni.do" screen="riconciliazioneTransazioni.screen" flow="true">
        <action-class>org.seda.payer.manager.riconciliazione.actions.RiconciliazioneTransazioniAction</action-class>
        <flow class="org.seda.payer.manager.riconciliazione.flows.RiconciliazioneTransazioniFlow">
        	<result value="ricerca" screen="riconciliazioneTransazioni.screen"/>
			<result value="stampa" writer="pdfMovimenti" content-type="application/pdf" inScope="false" attach="pdfMovimenti" />
        </flow>
          <ruleset>
			<rule name="codiceAbi" regex="codice5char_regex">
        		<missing severity="continue"/>
        		<malformed severity="fatal"/>
        	</rule>
			<rule name="codiceSia" regex="codice5char_regex">
        		<missing severity="continue"/>
        		<malformed severity="fatal"/>
        	</rule>
			<rule name="ccb" regex="codice12char_regex">
        		<missing severity="continue"/>
        		<malformed severity="fatal"/>
        	</rule>
			<rule name="nomeSupporto" regex="descrizione20_regex">
        		<missing severity="continue"/>
        		<malformed severity="fatal"/>
        	</rule>
<!-- 
			<rule name="importo_da" regex="num15_regex">
        		<missing severity="continue"/>
        		<malformed severity="fatal"/>
        	</rule>
			<rule name="importo_a" regex="num15_regex">
        		<missing severity="continue"/>
        		<malformed severity="fatal"/>
        	</rule>
 -->
           	<rule name="importo_da">
        		<validation>numberIT;maxlength=15</validation>
        		<missing severity="continue"/>
        		<malformed severity="fatal"/>
        	</rule>  
        	<rule name="importo_a">
        		<validation>numberIT;maxlength=15</validation>
        		<missing severity="continue"/>
        		<malformed severity="fatal"/>
        	</rule>  	
        </ruleset> 	
        		
    </action>

    <action url="riconciliazioneManualeTransazioni.do" screen="riconciliazioneManualeTransazioni.screen" flow="false">
        <action-class>org.seda.payer.manager.riconciliazione.actions.RiconciliazioneManualeTransazioniAction</action-class>
		<ruleset>
        	<rule name="codiceTransazione" regex="descrizione64_regex">
        		<missing severity="continue"/>
        		<malformed severity="fatal"/>
        	</rule>  
			<rule name="codiceAbi" regex="codice5char_regex">
        		<missing severity="continue"/>
        		<malformed severity="fatal"/>
        	</rule>
			<rule name="codiceSia" regex="codice5char_regex">
        		<missing severity="continue"/>
        		<malformed severity="fatal"/>
        	</rule>
			<rule name="ccb" regex="codice12char_regex">
        		<missing severity="continue"/>
        		<malformed severity="fatal"/>
        	</rule>
			<rule name="nomeSupporto" regex="descrizione20_regex">
        		<missing severity="continue"/>
        		<malformed severity="fatal"/>
        	</rule>
        </ruleset>
    </action>

	<action url="ritorna.do" flow="true">
		<description>Action per la gestione del ritorno ad altro screen con viewstate</description>
        <action-class>org.seda.payer.manager.riconciliazione.actions.RitornaAction</action-class>
        <flow class="org.seda.payer.manager.riconciliazione.flows.RitornaFlowManager">
           	<result value="riconciliazionemanualetransazioni" screen="riconciliazioneManualeTransazioni.do" />
        </flow>
    </action>  
    
    <action url="associaTransazione.do" screen="riconciliazioneManualeTransazioni.screen" flow="false">
        <action-class>org.seda.payer.manager.riconciliazione.actions.AssociaTransazioneAction</action-class>
    </action>
    
    <action url="eliminaAssociazione.do" screen="riconciliazioneManualeTransazioni.screen" flow="false">
        <action-class>org.seda.payer.manager.riconciliazione.actions.EliminaAssociazioneAction</action-class>
    </action>

    <action url="forzaChiusuraQuadratura.do" screen="riconciliazioneTransazioni.screen" flow="false">
        <action-class>org.seda.payer.manager.riconciliazione.actions.ForzaChiusuraQuadraturaAction</action-class>
    </action>
<!-- 
    <action url="impostaMovimentoRiferimento.do" screen="impostaMovimentoRiferimento.screen" flow="false">
        <action-class>org.seda.payer.manager.riconciliazione.actions.ImpostaMovimentoRiferimentoAction</action-class>
    </action>

    <action url="ricercaListaMovimenti.do" screen="ricercaListaMovimenti.screen" flow="false">
        <action-class>org.seda.payer.manager.riconciliazione.actions.RicercaListaMovimentiAction</action-class>
    </action>

    <action url="ricercaListaTransazioni.do" screen="ricercaListaTransazioni.screen" flow="false">
        <action-class>org.seda.payer.manager.riconciliazione.actions.RicercaListaTransazioniAction</action-class>
    </action>
 -->

    <action url="scaricaMovimento.do"  writer="true">
        <action-class>org.seda.payer.manager.riconciliazione.actions.ScaricaMovimentoAction</action-class>
		<!-- writer id="flussoCBI" content-type="plain/txt" inScope="true" attach="flussoCBI.txt"/ -->
		<writer id="flussoCBI" content-type="plain/txt" inScope="false" attach="flussoCBID"/>
    </action>

    <action url="dettaglioTransazione.do" screen="dettaglioTransazione.screen" flow="false">
        <action-class>org.seda.payer.manager.riconciliazione.actions.DettaglioTransazioneAction</action-class>
    </action>

    
</actions-mapping>
