=== regione-marche/org.seda.payer.manager.web/WebContent/WEB-INF/xsd/maf-templates.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
targetNamespace="http://template.core.maf.j2ee5.seda.com"
xmlns="http://template.core.maf.j2ee5.seda.com"
elementFormDefault="qualified">

<xsd:annotation>
 	<xsd:documentation xml:lang="en">
    </xsd:documentation>
</xsd:annotation>


<xsd:element name="templates" type="templatesType"/>

<xsd:complexType name="templatesType">
	<xsd:sequence>
		<xsd:element name="default" type="xsd:string" minOccurs="1" maxOccurs="1"/>	
		<xsd:element name="bundle" type="xsd:string" minOccurs="0" maxOccurs="1"/>		
		<xsd:element name="template" type="templateType"  minOccurs="0" maxOccurs="unbounded"/>		
		<xsd:element name="screen" type="screenType"  minOccurs="0" maxOccurs="unbounded"/>
    </xsd:sequence>
</xsd:complexType>

<xsd:complexType name="templateType">
	<xsd:sequence>
		<xsd:element name="url" type="xsd:string" minOccurs="1" maxOccurs="1"/>	
    </xsd:sequence>
    <xsd:attribute name="name" type="xsd:string" use="required"/>
        
</xsd:complexType>

<xsd:complexType name="screenType">
	<xsd:sequence>
		<xsd:element name="parameter" type="parameterType" minOccurs="1" maxOccurs="unbounded"/>	
    </xsd:sequence>
    <xsd:attribute name="name" type="xsd:string" use="required"/>    
    <xsd:attribute name="template" type="xsd:string"/>
    <xsd:attribute name="menuaction" type="xsd:string"/>        
</xsd:complexType>

<xsd:complexType name="parameterType">
    <xsd:attribute name="key" type="xsd:string" use="required"/>    
    <xsd:attribute name="value" type="xsd:string" use="required"/>    
    <xsd:attribute name="direct" type="xsd:string"/>    
	<xsd:attribute name="args" type="xsd:string"/>    
</xsd:complexType>

</xsd:schema>

=== regione-marche/org.seda.payer.manager.web/WebContent/applications/payer/blackboxconfig/maf-templates-bolzano.xml
<?xml version="1.0" encoding="UTF-8"?>
<templates xmlns="http://template.core.maf.j2ee5.seda.com"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://template.core.maf.j2ee5.seda.com ../../../WEB-INF/xsd/maf-templates.xsd">

	  <default>/applications/templates/default/default.jsp</default>
	
	  <bundle>org.seda.payer.manager.resources.TemplateStrings</bundle>
	  
	  <template name="errori">
		<url>/applications/templates/default/error_template.jsp</url>
	  </template>
	
	  <screen name="blackbox" template="default">
	    <parameter key="pagetitle" value="manager.blackbox.search.title" direct="true" />
	  	<parameter key="header" value="/applications/templates/shared/bolzano/header.jsp"/>
	    <parameter key="menu" value="/applications/templates/shared/menu.jsp" />
	    <parameter key="main" value="/applications/payer/blackboxconfig/bolzano/include/blackBox.jsp" />  <!-- LP PG210070 - 20210729 -->
	   <parameter key="footer" value="/applications/templates/shared/bolzano/footer.jsp"/>
	  </screen>
	   <screen name="blackboxEdit" template="default">
	    <parameter key="pagetitle" value="manager.blackbox.search.title" direct="true" />
	  	<parameter key="header" value="/applications/templates/shared/bolzano/header.jsp"/>
	    <parameter key="menu" value="/applications/templates/shared/menu.jsp" />
	    <parameter key="main" value="/applications/payer/blackboxconfig/bolzano/include/blackBoxEdit.jsp" />  <!-- LP PG210070 - 20210729 -->
	    <parameter key="footer" value="/applications/templates/shared/bolzano/footer.jsp"/>
	  </screen>
	  <screen name="blackboxCancel" template="default">
	    <parameter key="pagetitle" value="manager.blackbox.search.title" direct="true" />
	  	<parameter key="header" value="/applications/templates/shared/bolzano/header.jsp"/>
	    <parameter key="menu" value="/applications/templates/shared/menu.jsp" />
	    <parameter key="main" value="/applications/payer/blackboxconfig/include/blackbox_cancel.jsp" />
	    <parameter key="footer" value="/applications/templates/shared/bolzano/footer.jsp"/>
	  </screen>
	  
	  
  	  <screen name="blackboxpos" template="default">
	    <parameter key="pagetitle" value="manager.blackbox.search.title" direct="true" />
	  	<parameter key="header" value="/applications/templates/shared/bolzano/header.jsp"/>
	    <parameter key="menu" value="/applications/templates/shared/menu.jsp" />
	    <parameter key="main" value="/applications/payer/blackboxconfig/include/blackBoxPos.jsp" />
	   <parameter key="footer" value="/applications/templates/shared/bolzano/footer.jsp"/>
	  </screen>
	   <screen name="blackboxposEdit" template="default">
	    <parameter key="pagetitle" value="manager.blackbox.search.title" direct="true" />
	  	<parameter key="header" value="/applications/templates/shared/bolzano/header.jsp"/>
	    <parameter key="menu" value="/applications/templates/shared/menu.jsp" />
	    <parameter key="main" value="/applications/payer/blackboxconfig/include/blackBoxPosEdit.jsp" />
	    <parameter key="footer" value="/applications/templates/shared/bolzano/footer.jsp"/>
	  </screen>
	  <screen name="blackboxposDelete" template="default">
	    <parameter key="pagetitle" value="manager.blackbox.search.title" direct="true" />
	  	<parameter key="header" value="/applications/templates/shared/bolzano/header.jsp"/>
	    <parameter key="menu" value="/applications/templates/shared/menu.jsp" />
	    <parameter key="main" value="/applications/payer/blackboxconfig/include/blackBoxPosDelete.jsp" />
	    <parameter key="footer" value="/applications/templates/shared/bolzano/footer.jsp"/>
	  </screen>
	  
	  
   	  <screen name="blackboxposlog" template="default">
	    <parameter key="pagetitle" value="manager.blackbox.search.title" direct="true" />
	  	<parameter key="header" value="/applications/templates/shared/bolzano/header.jsp"/>
	    <parameter key="menu" value="/applications/templates/shared/menu.jsp" />
	    <parameter key="main" value="/applications/payer/blackboxconfig/include/blackBoxPosLog.jsp" />
	   <parameter key="footer" value="/applications/templates/shared/bolzano/footer.jsp"/>
	  </screen>
	  <screen name="blackboxposlogDelete" template="default">
	    <parameter key="pagetitle" value="manager.blackbox.search.title" direct="true" />
	  	<parameter key="header" value="/applications/templates/shared/bolzano/header.jsp"/>
	    <parameter key="menu" value="/applications/templates/shared/menu.jsp" />
	    <parameter key="main" value="/applications/payer/blackboxconfig/include/blackBoxPosLogDelete.jsp" />
	    <parameter key="footer" value="/applications/templates/shared/bolzano/footer.jsp"/>
	  </screen>

  </templates>

=== regione-marche/org.seda.payer.manager.web/WebContent/applications/payer/monitoraggio/maf-templates-creset.xml
<?xml version="1.0" encoding="UTF-8"?>
<templates xmlns="http://template.core.maf.j2ee5.seda.com"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://template.core.maf.j2ee5.seda.com ./../WEB-INF/xsd/maf-templates.xsd">

  <default>/applications/templates/default/default.jsp</default>

  <bundle>org.seda.payer.manager.resources.TemplateStrings</bundle>

  <template name="defaultUTF8">
		<url>/applications/templates/default/defaultUTF8.jsp</url>
  </template>
  
  <screen name="monitoraggioTransazioni" template="defaultUTF8">
    <parameter key="pagetitle" value="title.monitoraggio" direct="true" />
  	<parameter key="header" value="/applications/templates/shared/creset/header.jsp"/>
  	<parameter key="menu" value="/applications/templates/shared/menu.jsp" />
    <parameter key="main" value="/applications/payer/monitoraggio/creset/MonitoraggioTransazioni.jsp" />
    <parameter key="main2" value="/applications/payer/monitoraggio/creset/PopupDettaglioTransazione.jsp" />
  	<parameter key="footer" value="/applications/templates/shared/creset/footer.jsp"/>
  </screen>

  <screen name="modificaEmailSms" template="default">
    <parameter key="pagetitle" value="title.monitoraggio" direct="true" />
  	<parameter key="header" value="/applications/templates/shared/creset/header.jsp"/>
  	<parameter key="menu" value="/applications/templates/shared/menu.jsp" />
    <parameter key="main" value="/applications/payer/monitoraggio/creset/ModificaEmailSMSUtente.jsp" />
  	<parameter key="footer" value="/applications/templates/shared/creset/footer.jsp"/>
  </screen>

  <screen name="dettaglioTransazione" template="defaultUTF8">
    <parameter key="pagetitle" value="title.monitoraggio" direct="true" />
  	<parameter key="header" value="/applications/templates/shared/creset/header.jsp"/>
  	<parameter key="menu" value="/applications/templates/shared/menu.jsp" />
    <parameter key="main" value="/applications/payer/monitoraggio/creset/DettaglioTransazione.jsp" />
    <parameter key="main2" value="/applications/payer/monitoraggio/creset/ButtonDettaglioTransazione.jsp" />
  	<parameter key="footer" value="/applications/templates/shared/creset/footer.jsp"/>
  </screen>

  <screen name="forzaAllineamentoTransazione" template="default">
    <parameter key="pagetitle" value="title.monitoraggio" direct="true" />
  	<parameter key="header" value="/applications/templates/shared/creset/header.jsp"/>
  	<parameter key="menu" value="/applications/templates/shared/menu.jsp" />
    <parameter key="main" value="/applications/payer/monitoraggio/creset/ForzaAllineamentoTransazione.jsp" />
  	<parameter key="footer" value="/applications/templates/shared/creset/footer.jsp"/>
  </screen>
 
 <screen name="allineaManualmenteTransazione" template="default">
    <parameter key="pagetitle" value="title.monitoraggio" direct="true" />
  	<parameter key="header" value="/applications/templates/shared/creset/header.jsp"/>
  	<parameter key="menu" value="/applications/templates/shared/menu.jsp" />
    <parameter key="main" value="/applications/payer/monitoraggio/creset/AllineaManualmenteTransazione.jsp" />
  	<parameter key="footer" value="/applications/templates/shared/creset/footer.jsp"/>
  </screen> 
  
  <screen name="inviaNotificaAmministratore" template="default">
    <parameter key="pagetitle" value="title.monitoraggio" direct="true" />
  	<parameter key="header" value="/applications/templates/shared/creset/header.jsp"/>
  	<parameter key="menu" value="/applications/templates/shared/menu.jsp" />
    <parameter key="main" value="/applications/payer/monitoraggio/creset/InviaNotificaAmministratore.jsp" />
  	<parameter key="footer" value="/applications/templates/shared/creset/footer.jsp"/>
  </screen>
  
  <screen name="inviaNotificaContribuente" template="default">
    <parameter key="pagetitle" value="title.monitoraggio" direct="true"/>
  	<parameter key="header" value="/applications/templates/shared/creset/header.jsp"/>
  	<parameter key="menu" value="/applications/templates/shared/menu.jsp" />
    <parameter key="main" value="/applications/payer/monitoraggio/creset/InviaNotificaContribuente.jsp" />
  	<parameter key="footer" value="/applications/templates/shared/creset/footer.jsp"/>
  </screen>
  <!--<screen name="scaricaReportCSV" template="default">
    <parameter key="pagetitle" value="title.monitoraggio" direct="true" />
  	<parameter key="header" value="/applications/templates/shared/creset/header.jsp"/>
    <parameter key="main" value="/applications/payer/monitoraggio/creset/ScaricaReportCSV.jsp" />
  	<parameter key="footer" value="/applications/templates/shared/creset/footer.jsp"/>
  </screen>-->
  
  <screen name="stampaPDFBollettini" template="default">
    <parameter key="pagetitle" value="title.monitoraggio" direct="true" />
  	<parameter key="header" value="/applications/templates/shared/creset/header.jsp"/>
  	<parameter key="menu" value="/applications/templates/shared/menu.jsp" />
    <parameter key="main" value="/applications/payer/monitoraggio/creset/StampaPDFBollettini.jsp" />
  	<parameter key="footer" value="/applications/templates/shared/creset/footer.jsp"/>
  </screen>
 
  
  <!--<screen name="stampaReportPDF" template="default">
    <parameter key="pagetitle" value="title.monitoraggio" direct="true" />
  	<parameter key="header" value="/applications/templates/shared/creset/header.jsp"/>
    <parameter key="main" value="/applications/payer/monitoraggio/creset/StampaReportPDF.jsp" />
  	<parameter key="footer" value="/applications/templates/shared/creset/footer.jsp"/>
  </screen>-->
  
  <screen name="richiediRiconciliazione" template="default">
    <parameter key="pagetitle" value="title.monitoraggio" direct="true" />
  	<parameter key="header" value="/applications/templates/shared/creset/header.jsp"/>
  	<parameter key="menu" value="/applications/templates/shared/menu.jsp" />
    <parameter key="main" value="/applications/payer/monitoraggio/creset/RichiediRiconciliazione.jsp" />
  	<parameter key="footer" value="/applications/templates/shared/creset/footer.jsp"/>
  </screen>
  
</templates>

=== regione-marche/org.seda.payer.manager.web/WebContent/applications/payer/ottico/maf-templates-regmarche.xml
<?xml version="1.0" encoding="UTF-8"?>
<templates xmlns="http://template.core.maf.j2ee5.seda.com"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://template.core.maf.j2ee5.seda.com ../../../WEB-INF/xsd/maf-templates.xsd">

  <default>/applications/templates/default/regmarche/default.jsp</default>

  <bundle>org.seda.payer.manager.resources.TemplateStrings</bundle>

  <screen name="elaborazioni_search" template="default">
    <parameter key="pagetitle" value="manager.ottico.elaborazioni.search.title" direct="true"/>
  	<parameter key="header" value="/applications/templates/shared/regmarche/header.jsp"/>
    <parameter key="menu" value="/applications/templates/shared/menu.jsp" />
    <parameter key="main" value="/applications/payer/ottico/regmarche/elaborazioni/search.jsp" />
    <parameter key="results" value="/applications/payer/ottico/regmarche/elaborazioni/list.jsp" />
  	<parameter key="footer" value="/applications/templates/shared/regmarche/footer.jsp"/>
  </screen>

</templates>

=== regione-marche/org.seda.payer.manager.web/WebContent/applications/payer/ioitalia/maf-templates-bolzano.xml
<?xml version="1.0" encoding="UTF-8"?>
<templates xmlns="http://template.core.maf.j2ee5.seda.com"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://template.core.maf.j2ee5.seda.com ../../../WEB-INF/xsd/maf-templates.xsd">

	  <default>/applications/templates/default/default.jsp</default>
	
	  <bundle>org.seda.payer.manager.resources.TemplateStrings</bundle>
	  
	  <template name="errori">
		<url>/applications/templates/default/error_template.jsp</url>
	  </template>
	  
	  <template name="defaultUTF8">
		<url>/applications/templates/default/defaultUTF8.jsp</url>
	  </template>
	  
	  <!-- Start Screen Bolzano -->
	  
	  <screen name="ioitaliaconf" template="default">
	    <parameter key="pagetitle" value="manager.ioitalia.conf.title" direct="true" />
	  	<parameter key="header" value="/applications/templates/shared/bolzano/header.jsp"/>
	    <parameter key="menu" value="/applications/templates/shared/menu.jsp" />
	    <parameter key="main" value="/applications/payer/ioitalia/bolzano/include/ioitaliaconf.jsp" />
	   	<parameter key="footer" value="/applications/templates/shared/bolzano/footer.jsp"/>
	  </screen>
	  
	  <screen name="ioitaliaconfedit" template="default">
	    <parameter key="pagetitle" value="manager.ioitalia.conf.title" direct="true" />
	  	<parameter key="header" value="/applications/templates/shared/bolzano/header.jsp"/>
	    <parameter key="menu" value="/applications/templates/shared/menu.jsp" />
	    <parameter key="main" value="/applications/payer/ioitalia/bolzano/include/ioitaliaconfEdit.jsp" />
	   	<parameter key="footer" value="/applications/templates/shared/bolzano/footer.jsp"/>
	  </screen>
	  
	  <screen name="ioitalia" template="default">
	    <parameter key="pagetitle" value="manager.ioitalia.search.title" direct="true" />
	  	<parameter key="header" value="/applications/templates/shared/bolzano/header.jsp"/>
	    <parameter key="menu" value="/applications/templates/shared/menu.jsp" />
	    <parameter key="main" value="/applications/payer/ioitalia/bolzano/include/ioitalia.jsp" />
	   	<parameter key="footer" value="/applications/templates/shared/bolzano/footer.jsp"/>
	  </screen>
	  
	  <screen name="ioitaliaforniture" template="default">
	    <parameter key="pagetitle" value="manager.ioitalia.search.title" direct="true" />
	  	<parameter key="header" value="/applications/templates/shared/bolzano/header.jsp"/>
	    <parameter key="menu" value="/applications/templates/shared/menu.jsp" />
	    <parameter key="main" value="/applications/payer/ioitalia/bolzano/include/ioitaliaedit.jsp" />
	   	<parameter key="footer" value="/applications/templates/shared/bolzano/footer.jsp"/>
	  </screen>
	  
	  <screen name="ioitalianewmessage" template="defaultUTF8">
	    <parameter key="pagetitle" value="manager.ioitalia.search.title" direct="true" />
	  	<parameter key="header" value="/applications/templates/shared/bolzano/header.jsp"/>
	    <parameter key="menu" value="/applications/templates/shared/menu.jsp" />
	    <parameter key="main" value="/applications/payer/ioitalia/bolzano/include/ioitalianew.jsp" />
	   	<parameter key="footer" value="/applications/templates/shared/bolzano/footer.jsp"/>
	  </screen>
	  
	  <screen name="ioitaliamessageedit" template="defaultUTF8">
	    <parameter key="pagetitle" value="manager.ioitalia.search.title" direct="true" />
	  	<parameter key="header" value="/applications/templates/shared/bolzano/header.jsp"/>
	    <parameter key="menu" value="/applications/templates/shared/menu.jsp" />
	    <parameter key="main" value="/applications/payer/ioitalia/bolzano/include/ioitaliamessageedit.jsp" />
	   	<parameter key="footer" value="/applications/templates/shared/bolzano/footer.jsp"/>
	  </screen>
	  
	  <screen name="ioitaliaupload" template="default">
	    <parameter key="pagetitle" value="manager.ioitalia.upload.title" direct="true" />
	  	<parameter key="header" value="/applications/templates/shared/bolzano/header.jsp"/>
	    <parameter key="menu" value="/applications/templates/shared/menu.jsp" />
	    <parameter key="main" value="/applications/payer/ioitalia/bolzano/include/ioitaliacaricaCsv.jsp" />
	   	<parameter key="footer" value="/applications/templates/shared/bolzano/footer.jsp"/>
	  </screen> 
	  
	  <screen name="ioitaliamessaggiocancel" template="default">
	    <parameter key="pagetitle" value="manager.ioitalia.upload.title" direct="true" />
	  	<parameter key="header" value="/applications/templates/shared/aosta/header.jsp"/>
	    <parameter key="menu" value="/applications/templates/shared/menu.jsp" />
	    <parameter key="main" value="/applications/payer/ioitalia/include/messaggio_cancel.jsp" />
	   	<parameter key="footer" value="/applications/templates/shared/aosta/footer.jsp"/>
	  </screen>
	  
	  <screen name="ioitaliaconfigurazionecancel" template="default">
	    <parameter key="pagetitle" value="manager.ioitalia.upload.title" direct="true" />
	  	<parameter key="header" value="/applications/templates/shared/aosta/header.jsp"/>
	    <parameter key="menu" value="/applications/templates/shared/menu.jsp" />
	    <parameter key="main" value="/applications/payer/ioitalia/include/configurazione_cancel.jsp" />
	   	<parameter key="footer" value="/applications/templates/shared/aosta/footer.jsp"/>
	  </screen>
	  
  </templates>

=== regione-marche/org.seda.payer.manager.web/WebContent/applications/payer/serviziattivi/maf-templates-regmarche.xml
<?xml version="1.0" encoding="UTF-8"?>
<templates xmlns="http://template.core.maf.j2ee5.seda.com"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://template.core.maf.j2ee5.seda.com ../../../WEB-INF/xsd/maf-templates.xsd">
 
  <default>/applications/templates/default/regmarche/default.jsp</default>
  
  <bundle>org.seda.payer.manager.resources.TemplateStrings</bundle>
  

  <!-- SCREEN MANAGEMENT - serviziattivi TEMPLATE > SERVIZI ATTIVI PG200360 -->
  
   <screen name="serviziattivi_search" template="default">
    <parameter key="pagetitle" value="manager.serviziattivi.search.title" direct="true"/>
  	<parameter key="header" value="/applications/templates/shared/regmarche/header.jsp"/>
    <parameter key="menu" value="/applications/templates/shared/menu.jsp" />
    <parameter key="main" value="/applications/payer/serviziattivi/regmarche/include/serviziattivi_search.jsp" />
    <parameter key="results" value="/applications/payer/serviziattivi/regmarche/include/serviziattivi_list.jsp" />
  	<parameter key="footer" value="/applications/templates/shared/regmarche/footer.jsp"/>
  </screen>
 
 <screen name="serviziattivi_edit" template="default">
    <parameter key="pagetitle" value="manager.serviziattivi.edit.title" direct="true"/>
    <parameter key="contenttitle" value="manager.serviziattivi.edit.title" direct="true"/>
  	<parameter key="header" value="/applications/templates/shared/regmarche/header.jsp"/>
    <parameter key="menu" value="/applications/templates/shared/menu.jsp" />
    <parameter key="main" value="/applications/payer/serviziattivi/regmarche/include/serviziattivi_var.jsp" />        
  	<parameter key="footer" value="/applications/templates/shared/regmarche/footer.jsp"/>
  </screen>

  <!-- FINE LP PG200360 -->
  
</templates>

=== regione-marche/org.seda.payer.manager.web/WebContent/applications/payer/adminusers/maf-templates-lepida.xml
<?xml version="1.0" encoding="UTF-8"?>
<templates xmlns="http://template.core.maf.j2ee5.seda.com"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://template.core.maf.j2ee5.seda.com ../../../WEB-INF/xsd/maf-templates.xsd">

  <default>/applications/templates/default/default.jsp</default>
  
  <bundle>org.seda.payer.manager.resources.TemplateStrings</bundle>
  
  <template name="errori">
	<url>/applications/templates/default/error_template.jsp</url>
  </template>
  

  <screen name="adminusers_search" template="default">
	<parameter key="pagetitle" value="manager.adminusers.search.title" direct="true"/>
    <parameter key="header" value="/applications/templates/shared/lepida/header.jsp" />
    <parameter key="menu" value="/applications/templates/shared/menu.jsp" />
    <parameter key="main" value="/applications/payer/adminusers/include/adminusers_search_lepida.jsp" />
    <parameter key="results" value="/applications/payer/adminusers/include/messages.jsp" />
    <parameter key="footer" value="/applications/templates/shared/lepida/footer.jsp" />
  </screen>

  <screen name="adminusers_add" template="default">
	<parameter key="pagetitle" value="manager.adminusers.add.title" direct="true"/>
    <parameter key="header" value="/applications/templates/shared/lepida/header.jsp" />
    <parameter key="menu" value="/applications/templates/shared/menu.jsp" />
    <parameter key="main" value="/applications/payer/adminusers/include/adminusers_var_lepida.jsp" />
    <parameter key="results" value="/applications/payer/adminusers/include/messages.jsp" />
    <parameter key="footer" value="/applications/templates/shared/lepida/footer.jsp" />
  </screen>

  <screen name="adminusers_add2" template="default">
	<parameter key="pagetitle" value="manager.adminusers.add2.title" direct="true"/>
    <parameter key="header" value="/applications/templates/shared/lepida/header.jsp" />
    <parameter key="menu" value="/applications/templates/shared/menu.jsp" />
    <parameter key="main" value="/applications/payer/adminusers/include/adminusers_var2_lepida.jsp" />
    <parameter key="results" value="/applications/payer/adminusers/include/messages.jsp" />
    <parameter key="footer" value="/applications/templates/shared/lepida/footer.jsp" />
  </screen>

  <screen name="adminusers_edit" template="default">
	<parameter key="pagetitle" value="manager.adminusers.edit.title" direct="true"/>
    <parameter key="header" value="/applications/templates/shared/lepida/header.jsp" />
    <parameter key="menu" value="/applications/templates/shared/menu.jsp" />
    <parameter key="main" value="/applications/payer/adminusers/include/adminusers_var_lepida.jsp" />
    <parameter key="results" value="/applications/payer/adminusers/include/messages.jsp" />
    <parameter key="footer" value="/applications/templates/shared/lepida/footer.jsp" />
  </screen>

  <screen name="adminusers_edit2" template="default">
	<parameter key="pagetitle" value="manager.adminusers.edit2.title" direct="true"/>
    <parameter key="header" value="/applications/templates/shared/lepida/header.jsp" />
    <parameter key="menu" value="/applications/templates/shared/menu.jsp" />
    <parameter key="main" value="/applications/payer/adminusers/include/adminusers_var2_lepida.jsp" />
    <parameter key="results" value="/applications/payer/adminusers/include/messages.jsp" />
    <parameter key="footer" value="/applications/templates/shared/lepida/footer.jsp" />
  </screen>

  <screen name="adminusers_canc" template="default">
	<parameter key="pagetitle" value="manager.adminusers.canc.title" direct="true"/>
    <parameter key="header" value="/applications/templates/shared/lepida/header.jsp" />
    <parameter key="menu" value="/applications/templates/shared/menu.jsp" />
    <parameter key="main" value="/applications/payer/adminusers/include/adminusers_canc.jsp" />
    <parameter key="results" value="/applications/payer/adminusers/include/messages.jsp" />
    <parameter key="footer" value="/applications/templates/shared/lepida/footer.jsp" />
  </screen>


<!-- GESTIONE UTENZE INIZIO -->

  <screen name="seUsers_add" template="default">
	<parameter key="pagetitle" value="manager.seusers.add.title" direct="true"/>
    <parameter key="header" value="/applications/templates/shared/lepida/header.jsp" />
    <parameter key="menu" value="/applications/templates/shared/menu.jsp" />
    <parameter key="main" value="/applications/payer/adminusers/include/seUsers_var_lepida.jsp" />
    <parameter key="results" value="/applications/payer/adminusers/include/messages.jsp" />
    <parameter key="footer" value="/applications/templates/shared/lepida/footer.jsp" />
  </screen>

  <screen name="seUsers_edit" template="default">
	<parameter key="pagetitle" value="manager.seusers.edit.title" direct="true"/>
    <parameter key="header" value="/applications/templates/shared/lepida/header.jsp" />
    <parameter key="menu" value="/applications/templates/shared/menu.jsp" />
    <parameter key="main" value="/applications/payer/adminusers/include/seUsers_var_lepida.jsp" />
    <parameter key="results" value="/applications/payer/adminusers/include/messages.jsp" />
    <parameter key="footer" value="/applications/templates/shared/lepida/footer.jsp" />
  </screen>

  <screen name="seUsers_search" template="default">
	<parameter key="pagetitle" value="manager.seusers.search.title" direct="true"/>
    <parameter key="header" value="/applications/templates/shared/lepida/header.jsp" />
    <parameter key="menu" value="/applications/templates/shared/menu.jsp" />
    <parameter key="main" value="/applications/payer/adminusers/include/seUsers_search_lepida.jsp" />
    <parameter key="results" value="/applications/payer/adminusers/include/messages.jsp" />
    <parameter key="footer" value="/applications/templates/shared/lepida/footer.jsp" />
  </screen>

  <screen name="seUsers_sblocca" template="default">
	<parameter key="pagetitle" value="manager.seusers.sblocca.title" direct="true"/>
    <parameter key="header" value="/applications/templates/shared/lepida/header.jsp" />
    <parameter key="menu" value="/applications/templates/shared/menu.jsp" />
    <parameter key="main" value="/applications/payer/adminusers/include/seUsers_sblocca.jsp" />
    <parameter key="results" value="/applications/payer/adminusers/include/messages.jsp" />
    <parameter key="footer" value="/applications/templates/shared/lepida/footer.jsp" />
  </screen>

  <screen name="seusers_resetpswd" template="default">
	<parameter key="pagetitle" value="manager.adminusers.resetpswd.title" direct="true"/>
    <parameter key="header" value="/applications/templates/shared/lepida/header.jsp" />
    <parameter key="main" value="/applications/payer/adminusers/include/messages.jsp" />
    <parameter key="results" value="/applications/payer/adminusers/include/seUsers_reset_pswd.jsp" />
    <parameter key="footer" value="/applications/templates/shared/lepida/footer.jsp" />
  </screen>

<!-- GESTIONE UTENZE FINE -->

  <screen name="error" template="errori">
  	<parameter key="header" value="/applications/templates/shared/lepida/header.jsp"/>
	<parameter key="content" value="/applications/templates/shared/error_content.jsp" />
  	<parameter key="footer" value="/applications/templates/shared/lepida/footer.jsp"/>
  </screen>  


</templates>
