=== regione-marche/org.seda.payer.manager.web/WebContent/WEB-INF/xsd/maf-templates.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
targetNamespace="http://template.core.maf.j2ee5.seda.com"
xmlns="http://template.core.maf.j2ee5.seda.com"
elementFormDefault="qualified">

<xsd:annotation>
 	<xsd:documentation xml:lang="en">
    </xsd:documentation>
</xsd:annotation>


<xsd:element name="templates" type="templatesType"/>

<xsd:complexType name="templatesType">
	<xsd:sequence>
		<xsd:element name="default" type="xsd:string" minOccurs="1" maxOccurs="1"/>	
		<xsd:element name="bundle" type="xsd:string" minOccurs="0" maxOccurs="1"/>		
		<xsd:element name="template" type="templateType"  minOccurs="0" maxOccurs="unbounded"/>		
		<xsd:element name="screen" type="screenType"  minOccurs="0" maxOccurs="unbounded"/>
    </xsd:sequence>
</xsd:complexType>

<xsd:complexType name="templateType">
	<xsd:sequence>
		<xsd:element name="url" type="xsd:string" minOccurs="1" maxOccurs="1"/>	
    </xsd:sequence>
    <xsd:attribute name="name" type="xsd:string" use="required"/>
        
</xsd:complexType>

<xsd:complexType name="screenType">
	<xsd:sequence>
		<xsd:element name="parameter" type="parameterType" minOccurs="1" maxOccurs="unbounded"/>	
    </xsd:sequence>
    <xsd:attribute name="name" type="xsd:string" use="required"/>    
    <xsd:attribute name="template" type="xsd:string"/>
    <xsd:attribute name="menuaction" type="xsd:string"/>        
</xsd:complexType>

<xsd:complexType name="parameterType">
    <xsd:attribute name="key" type="xsd:string" use="required"/>    
    <xsd:attribute name="value" type="xsd:string" use="required"/>    
    <xsd:attribute name="direct" type="xsd:string"/>    
	<xsd:attribute name="args" type="xsd:string"/>    
</xsd:complexType>

</xsd:schema>

=== regione-marche/org.seda.payer.manager.web/WebContent/applications/payer/wismanager/maf-templates-padanatech.xml
<?xml version="1.0" encoding="UTF-8"?>
<templates xmlns="http://template.core.maf.j2ee5.seda.com"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://template.core.maf.j2ee5.seda.com ./../WEB-INF/xsd/maf-templates.xsd">

  <default>/applications/templates/default/default.jsp</default>
  
  <bundle>org.seda.payer.manager.resources.TemplateStrings</bundle>

  <screen name="wismanager" template="default">
    <parameter key="pagetitle" value="title.wismanager" direct="true"/>
  	<parameter key="header" value="/applications/templates/shared/padanatech/header.jsp"/>
    <parameter key="menu" value="/applications/templates/shared/menu.jsp" />
    <parameter key="main" value="/applications/payer/wismanager/include/wismanager.jsp" />
  	<parameter key="footer" value="/applications/templates/shared/padanatech/footer.jsp"/>
  </screen>

  
</templates>

=== regione-marche/org.seda.payer.manager.web/WebContent/applications/payer/monitoraggio/maf-templates-roseto.xml
<?xml version="1.0" encoding="UTF-8"?>
<templates xmlns="http://template.core.maf.j2ee5.seda.com"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://template.core.maf.j2ee5.seda.com ./../WEB-INF/xsd/maf-templates.xsd">

  <default>/applications/templates/default/default.jsp</default>

  <bundle>org.seda.payer.manager.resources.TemplateStrings</bundle>

  <template name="defaultUTF8">
		<url>/applications/templates/default/defaultUTF8.jsp</url>
  </template>
  
  <screen name="monitoraggioTransazioni" template="defaultUTF8">
    <parameter key="pagetitle" value="title.monitoraggio" direct="true" />
  	<parameter key="header" value="/applications/templates/shared/roseto/header.jsp"/>
  	<parameter key="menu" value="/applications/templates/shared/menu.jsp" />
    <parameter key="main" value="/applications/payer/monitoraggio/roseto/MonitoraggioTransazioni.jsp" />
    <parameter key="main2" value="/applications/payer/monitoraggio/roseto/PopupDettaglioTransazione.jsp" />
  	<parameter key="footer" value="/applications/templates/shared/roseto/footer.jsp"/>
  </screen>

  <screen name="modificaEmailSms" template="default">
    <parameter key="pagetitle" value="title.monitoraggio" direct="true" />
  	<parameter key="header" value="/applications/templates/shared/roseto/header.jsp"/>
  	<parameter key="menu" value="/applications/templates/shared/menu.jsp" />
    <parameter key="main" value="/applications/payer/monitoraggio/roseto/ModificaEmailSMSUtente.jsp" />
  	<parameter key="footer" value="/applications/templates/shared/roseto/footer.jsp"/>
  </screen>

  <screen name="dettaglioTransazione" template="defaultUTF8">
    <parameter key="pagetitle" value="title.monitoraggio" direct="true" />
  	<parameter key="header" value="/applications/templates/shared/roseto/header.jsp"/>
  	<parameter key="menu" value="/applications/templates/shared/menu.jsp" />
    <parameter key="main" value="/applications/payer/monitoraggio/roseto/DettaglioTransazione.jsp" />
    <parameter key="main2" value="/applications/payer/monitoraggio/roseto/ButtonDettaglioTransazione.jsp" />
  	<parameter key="footer" value="/applications/templates/shared/roseto/footer.jsp"/>
  </screen>

  <screen name="forzaAllineamentoTransazione" template="default">
    <parameter key="pagetitle" value="title.monitoraggio" direct="true" />
  	<parameter key="header" value="/applications/templates/shared/roseto/header.jsp"/>
  	<parameter key="menu" value="/applications/templates/shared/menu.jsp" />
    <parameter key="main" value="/applications/payer/monitoraggio/roseto/ForzaAllineamentoTransazione.jsp" />
  	<parameter key="footer" value="/applications/templates/shared/roseto/footer.jsp"/>
  </screen>
 
 <screen name="allineaManualmenteTransazione" template="default">
    <parameter key="pagetitle" value="title.monitoraggio" direct="true" />
  	<parameter key="header" value="/applications/templates/shared/roseto/header.jsp"/>
  	<parameter key="menu" value="/applications/templates/shared/menu.jsp" />
    <parameter key="main" value="/applications/payer/monitoraggio/roseto/AllineaManualmenteTransazione.jsp" />
  	<parameter key="footer" value="/applications/templates/shared/roseto/footer.jsp"/>
  </screen> 
  
  <screen name="inviaNotificaAmministratore" template="default">
    <parameter key="pagetitle" value="title.monitoraggio" direct="true" />
  	<parameter key="header" value="/applications/templates/shared/roseto/header.jsp"/>
  	<parameter key="menu" value="/applications/templates/shared/menu.jsp" />
    <parameter key="main" value="/applications/payer/monitoraggio/roseto/InviaNotificaAmministratore.jsp" />
  	<parameter key="footer" value="/applications/templates/shared/roseto/footer.jsp"/>
  </screen>
  
  <screen name="inviaNotificaContribuente" template="default">
    <parameter key="pagetitle" value="title.monitoraggio" direct="true"/>
  	<parameter key="header" value="/applications/templates/shared/roseto/header.jsp"/>
  	<parameter key="menu" value="/applications/templates/shared/menu.jsp" />
    <parameter key="main" value="/applications/payer/monitoraggio/roseto/InviaNotificaContribuente.jsp" />
  	<parameter key="footer" value="/applications/templates/shared/roseto/footer.jsp"/>
  </screen>
  <!--<screen name="scaricaReportCSV" template="default">
    <parameter key="pagetitle" value="title.monitoraggio" direct="true" />
  	<parameter key="header" value="/applications/templates/shared/roseto/header.jsp"/>
    <parameter key="main" value="/applications/payer/monitoraggio/roseto/ScaricaReportCSV.jsp" />
  	<parameter key="footer" value="/applications/templates/shared/roseto/footer.jsp"/>
  </screen>-->
  
  <screen name="stampaPDFBollettini" template="default">
    <parameter key="pagetitle" value="title.monitoraggio" direct="true" />
  	<parameter key="header" value="/applications/templates/shared/roseto/header.jsp"/>
  	<parameter key="menu" value="/applications/templates/shared/menu.jsp" />
    <parameter key="main" value="/applications/payer/monitoraggio/roseto/StampaPDFBollettini.jsp" />
  	<parameter key="footer" value="/applications/templates/shared/roseto/footer.jsp"/>
  </screen>
 
  
  <!--<screen name="stampaReportPDF" template="default">
    <parameter key="pagetitle" value="title.monitoraggio" direct="true" />
  	<parameter key="header" value="/applications/templates/shared/roseto/header.jsp"/>
    <parameter key="main" value="/applications/payer/monitoraggio/roseto/StampaReportPDF.jsp" />
  	<parameter key="footer" value="/applications/templates/shared/roseto/footer.jsp"/>
  </screen>-->
  
  <screen name="richiediRiconciliazione" template="default">
    <parameter key="pagetitle" value="title.monitoraggio" direct="true" />
  	<parameter key="header" value="/applications/templates/shared/roseto/header.jsp"/>
  	<parameter key="menu" value="/applications/templates/shared/menu.jsp" />
    <parameter key="main" value="/applications/payer/monitoraggio/roseto/RichiediRiconciliazione.jsp" />
  	<parameter key="footer" value="/applications/templates/shared/roseto/footer.jsp"/>
  </screen>
  
</templates>

=== regione-marche/org.seda.payer.manager.web/WebContent/applications/payer/login/maf-templates-creset.xml
<?xml version="1.0" encoding="UTF-8"?>

<templates xmlns="http://template.core.maf.j2ee5.seda.com"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://template.core.maf.j2ee5.seda.com ../../../WEB-INF/xsd/maf-templates.xsd">

  <default>/applications/templates/login/LoginTemplate.jsp</default>

 	<bundle>org.seda.payer.manager.resources.TemplateStrings</bundle>

  	<template name="login">
  		<url>/applications/templates/login/LoginTemplate.jsp</url>
  	</template>
  
  	<template name="password">
  		<url>/applications/templates/default/default.jsp</url>
  	</template>

  	<screen name="login" template="login">
  	    <parameter key="pagetitle" value="manager.login.title" direct="true"/>
		<parameter key="header" value="/applications/templates/shared/creset/header.jsp" />
		<parameter key="content" value="/applications/payer/login/include/login.jsp"  />
		<parameter key="footer" value="/applications/templates/shared/creset/footer.jsp" />
	</screen>
	
	<screen name="login_error" template="login">
	    <parameter key="pagetitle" value="credentials.login.error.pagetitle" direct="true" /> 
  		<parameter key="header" value="/applications/templates/shared/creset/header.jsp" /> 
  		<parameter key="content" value="/applications/payer/login/include/login_error.jsp" /> 
  		<parameter key="footer" value="/applications/templates/shared/creset/footer.jsp" /> 
	</screen>
	
 <screen name="resetpswd" template="password">
	<parameter key="pagetitle" value="manager.default.resetpswd.title" direct="true"/>
    <parameter key="header" value="/applications/templates/shared/creset/header.jsp" />
    <parameter key="main" value="/applications/payer/login/include/resetpswd.jsp" />
    <parameter key="results" value="/applications/payer/login/include/messages.jsp" />
    <parameter key="footer" value="/applications/templates/shared/creset/footer.jsp" />
  </screen>

  <screen name="cambiopswd" template="password">
	<parameter key="pagetitle" value="manager.default.cambiopswd.title" direct="true"/>
    <parameter key="header" value="/applications/templates/shared/creset/header.jsp" />
    <parameter key="main" value="/applications/payer/login/include/cambiopswd.jsp" />
    <parameter key="results" value="/applications/payer/login/include/messages.jsp" />
    <parameter key="footer" value="/applications/templates/shared/creset/footer.jsp" />
  </screen>
  
  <screen name="loginerror" template="login">
 	<parameter key="pagetitle" value="manager.login.title" direct="true"/>
	<parameter key="header" value="/applications/templates/shared/creset/header.jsp" />
	<parameter key="content" value="/applications/payer/login/include/login.jsp"  />
	<parameter key="footer" value="/applications/templates/shared/creset/footer.jsp" />
  </screen>
	
</templates>

=== regione-marche/org.seda.payer.manager.web/WebContent/applications/payer/monitoraggio/maf-templates-bolzano.xml
<?xml version="1.0" encoding="UTF-8"?>
<templates xmlns="http://template.core.maf.j2ee5.seda.com"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://template.core.maf.j2ee5.seda.com ./../WEB-INF/xsd/maf-templates.xsd">

  <default>/applications/templates/default/default.jsp</default>

  <bundle>org.seda.payer.manager.resources.TemplateStrings</bundle>

  <template name="defaultUTF8">
		<url>/applications/templates/default/defaultUTF8.jsp</url>
  </template>
  
  <screen name="monitoraggioTransazioni" template="defaultUTF8">
    <parameter key="pagetitle" value="title.monitoraggio" direct="true" />
  	<parameter key="header" value="/applications/templates/shared/bolzano/header.jsp"/>
  	<parameter key="menu" value="/applications/templates/shared/menu.jsp" />
    <parameter key="main" value="/applications/payer/monitoraggio/bolzano/MonitoraggioTransazioni.jsp" />
    <parameter key="main2" value="/applications/payer/monitoraggio/bolzano/PopupDettaglioTransazione.jsp" />
  	<parameter key="footer" value="/applications/templates/shared/bolzano/footer.jsp"/>
  </screen>

  <screen name="modificaEmailSms" template="default">
    <parameter key="pagetitle" value="title.monitoraggio" direct="true" />
  	<parameter key="header" value="/applications/templates/shared/bolzano/header.jsp"/>
  	<parameter key="menu" value="/applications/templates/shared/menu.jsp" />
    <parameter key="main" value="/applications/payer/monitoraggio/include/ModificaEmailSMSUtente.jsp" />
  	<parameter key="footer" value="/applications/templates/shared/bolzano/footer.jsp"/>
  </screen>

  <screen name="dettaglioTransazione" template="defaultUTF8">
    <parameter key="pagetitle" value="title.monitoraggio" direct="true" />
  	<parameter key="header" value="/applications/templates/shared/bolzano/header.jsp"/>
  	<parameter key="menu" value="/applications/templates/shared/menu.jsp" />
    <parameter key="main" value="/applications/payer/monitoraggio/bolzano/DettaglioTransazione.jsp" />
    <parameter key="main2" value="/applications/payer/monitoraggio/include/ButtonDettaglioTransazione.jsp" />
  	<parameter key="footer" value="/applications/templates/shared/bolzano/footer.jsp"/>
  </screen>

  <screen name="forzaAllineamentoTransazione" template="default">
    <parameter key="pagetitle" value="title.monitoraggio" direct="true" />
  	<parameter key="header" value="/applications/templates/shared/bolzano/header.jsp"/>
  	<parameter key="menu" value="/applications/templates/shared/menu.jsp" />
    <parameter key="main" value="/applications/payer/monitoraggio/include/ForzaAllineamentoTransazione.jsp" />
  	<parameter key="footer" value="/applications/templates/shared/bolzano/footer.jsp"/>
  </screen>
 
  <screen name="allineaManualmenteTransazione" template="default">
    <parameter key="pagetitle" value="title.monitoraggio" direct="true" />
  	<parameter key="header" value="/applications/templates/shared/bolzano/header.jsp"/>
  	<parameter key="menu" value="/applications/templates/shared/menu.jsp" />
    <parameter key="main" value="/applications/payer/monitoraggio/include/AllineaManualmenteTransazione.jsp" />
  	<parameter key="footer" value="/applications/templates/shared/bolzano/footer.jsp"/>
  </screen>
  
  <screen name="inviaNotificaAmministratore" template="default">
    <parameter key="pagetitle" value="title.monitoraggio" direct="true" />
  	<parameter key="header" value="/applications/templates/shared/bolzano/header.jsp"/>
  	<parameter key="menu" value="/applications/templates/shared/menu.jsp" />
    <parameter key="main" value="/applications/payer/monitoraggio/include/InviaNotificaAmministratore.jsp" />
  	<parameter key="footer" value="/applications/templates/shared/bolzano/footer.jsp"/>
  </screen>
  
  <screen name="inviaNotificaContribuente" template="default">
    <parameter key="pagetitle" value="title.monitoraggio" direct="true"/>
  	<parameter key="header" value="/applications/templates/shared/bolzano/header.jsp"/>
  	<parameter key="menu" value="/applications/templates/shared/menu.jsp" />
    <parameter key="main" value="/applications/payer/monitoraggio/include/InviaNotificaContribuente.jsp" />
  	<parameter key="footer" value="/applications/templates/shared/bolzano/footer.jsp"/>
  </screen>
  <!--<screen name="scaricaReportCSV" template="default">
    <parameter key="pagetitle" value="title.monitoraggio" direct="true" />
  	<parameter key="header" value="/applications/templates/shared/bolzano/header.jsp"/>
    <parameter key="main" value="/applications/payer/monitoraggio/include/ScaricaReportCSV.jsp" />
  	<parameter key="footer" value="/applications/templates/shared/bolzano/footer.jsp"/>
  </screen>-->
  
  <screen name="stampaPDFBollettini" template="default">
    <parameter key="pagetitle" value="title.monitoraggio" direct="true" />
  	<parameter key="header" value="/applications/templates/shared/bolzano/header.jsp"/>
  	<parameter key="menu" value="/applications/templates/shared/menu.jsp" />
    <parameter key="main" value="/applications/payer/monitoraggio/include/StampaPDFBollettini.jsp" />
  	<parameter key="footer" value="/applications/templates/shared/bolzano/footer.jsp"/>
  </screen>
 
  
  <!--<screen name="stampaReportPDF" template="default">
    <parameter key="pagetitle" value="title.monitoraggio" direct="true" />
  	<parameter key="header" value="/applications/templates/shared/bolzano/header.jsp"/>
    <parameter key="main" value="/applications/payer/monitoraggio/include/StampaReportPDF.jsp" />
  	<parameter key="footer" value="/applications/templates/shared/bolzano/footer.jsp"/>
  </screen>-->
  
  <screen name="richiediRiconciliazione" template="default">
    <parameter key="pagetitle" value="title.monitoraggio" direct="true" />
  	<parameter key="header" value="/applications/templates/shared/bolzano/header.jsp"/>
  	<parameter key="menu" value="/applications/templates/shared/menu.jsp" />
    <parameter key="main" value="/applications/payer/monitoraggio/include/RichiediRiconciliazione.jsp" />
  	<parameter key="footer" value="/applications/templates/shared/bolzano/footer.jsp"/>
  </screen>
  
</templates>

=== regione-marche/org.seda.payer.manager.web/WebContent/applications/payer/ottico/maf-templates-roseto.xml
<?xml version="1.0" encoding="UTF-8"?>
<templates xmlns="http://template.core.maf.j2ee5.seda.com"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://template.core.maf.j2ee5.seda.com ../../../WEB-INF/xsd/maf-templates.xsd">

  <default>/applications/templates/default/default.jsp</default>

  <bundle>org.seda.payer.manager.resources.TemplateStrings</bundle>

  <screen name="elaborazioni_search" template="default">
    <parameter key="pagetitle" value="manager.ottico.elaborazioni.search.title" direct="true"/>
  	<parameter key="header" value="/applications/templates/shared/roseto/header.jsp"/>
    <parameter key="menu" value="/applications/templates/shared/menu.jsp" />
    <parameter key="main" value="/applications/payer/ottico/include/elaborazioni/search.jsp" />
    <parameter key="results" value="/applications/payer/ottico/include/elaborazioni/list.jsp" />
  	<parameter key="footer" value="/applications/templates/shared/roseto/footer.jsp"/>
  </screen>

</templates>

=== regione-marche/org.seda.payer.manager.web/WebContent/applications/payer/integrazioneflussi/maf-templates-regmarche.xml
<?xml version="1.0" encoding="UTF-8"?>
<templates xmlns="http://template.core.maf.j2ee5.seda.com"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://template.core.maf.j2ee5.seda.com ../../../WEB-INF/xsd/maf-templates.xsd">

	  <default>/applications/templates/default/regmarche/default.jsp</default>
	
	  <bundle>org.seda.payer.manager.resources.TemplateStrings</bundle>
	  
	  <template name="errori">
		<url>/applications/templates/default/error_template.jsp</url>
	  </template>
	
	  <screen name="integrazioneflussi" template="default">
	    <parameter key="pagetitle" value="manager.integrazioneflussi.search.title" direct="true" />
	  	<parameter key="header" value="/applications/templates/shared/regmarche/header.jsp"/>
	    <parameter key="menu" value="/applications/templates/shared/menu.jsp" />
	    <parameter key="main" value="/applications/payer/integrazioneflussi/regmarche/include/integrazioneflussi.jsp" />
	   	<parameter key="footer" value="/applications/templates/shared/regmarche/footer.jsp"/>
	  </screen>
	  
	  <screen name="integrazioneflussidettagli" template="default">
	    <parameter key="pagetitle" value="manager.integrazioneflussi.search.title" direct="true" />
	  	<parameter key="header" value="/applications/templates/shared/regmarche/header.jsp"/>
	    <parameter key="menu" value="/applications/templates/shared/menu.jsp" />
	    <parameter key="main" value="/applications/payer/integrazioneflussi/regmarche/include/integrazioneflussidettagli.jsp" />
	   	<parameter key="footer" value="/applications/templates/shared/regmarche/footer.jsp"/>
	  </screen>
	  
	  <screen name="integrazioneflussidettaglio" template="default">
	    <parameter key="pagetitle" value="manager.integrazioneflussi.search.title" direct="true" />
	  	<parameter key="header" value="/applications/templates/shared/regmarche/header.jsp"/>
	    <parameter key="menu" value="/applications/templates/shared/menu.jsp" />
	    <parameter key="main" value="/applications/payer/integrazioneflussi/regmarche/include/integrazioneflussidettaglio.jsp" />
	   	<parameter key="footer" value="/applications/templates/shared/regmarche/footer.jsp"/>
	  </screen>
	  
  </templates>

=== regione-marche/org.seda.payer.manager.web/WebContent/applications/payer/ioitalia/maf-templates.xml
<?xml version="1.0" encoding="UTF-8"?>
<templates xmlns="http://template.core.maf.j2ee5.seda.com"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://template.core.maf.j2ee5.seda.com ../../../WEB-INF/xsd/maf-templates.xsd">

	  <default>/applications/templates/default/default.jsp</default>
	
	  <bundle>org.seda.payer.manager.resources.TemplateStrings</bundle>
	  
	  <template name="errori">
		<url>/applications/templates/default/error_template.jsp</url>
	  </template>
	
	  <screen name="ioitaliaconf" template="default">
	    <parameter key="pagetitle" value="manager.ioitalia.conf.title" direct="true" />
	  	<parameter key="header" value="/applications/templates/shared/aosta/header.jsp"/>
	    <parameter key="menu" value="/applications/templates/shared/menu.jsp" />
	    <parameter key="main" value="/applications/payer/ioitalia/aosta/include/ioitaliaconf.jsp" />
	   	<parameter key="footer" value="/applications/templates/shared/aosta/footer.jsp"/>
	  </screen>
	  
	  <screen name="ioitalia" template="default">
	    <parameter key="pagetitle" value="manager.ioitalia.search.title" direct="true" />
	  	<parameter key="header" value="/applications/templates/shared/aosta/header.jsp"/>
	    <parameter key="menu" value="/applications/templates/shared/menu.jsp" />
	    <parameter key="main" value="/applications/payer/ioitalia/aosta/include/ioitalia.jsp" />
	   	<parameter key="footer" value="/applications/templates/shared/aosta/footer.jsp"/>
	  </screen>
	  
	  <screen name="ioitaliaforniture" template="default">
	    <parameter key="pagetitle" value="manager.ioitalia.search.title" direct="true" />
	  	<parameter key="header" value="/applications/templates/shared/aosta/header.jsp"/>
	    <parameter key="menu" value="/applications/templates/shared/menu.jsp" />
	    <parameter key="main" value="/applications/payer/ioitalia/aosta/include/ioitaliaedit.jsp" />
	   	<parameter key="footer" value="/applications/templates/shared/aosta/footer.jsp"/>
	  </screen>
	  
	  <screen name="ioitaliaconfedit" template="default">
	    <parameter key="pagetitle" value="manager.ioitalia.conf.title" direct="true" />
	  	<parameter key="header" value="/applications/templates/shared/aosta/header.jsp"/>
	    <parameter key="menu" value="/applications/templates/shared/menu.jsp" />
	    <parameter key="main" value="/applications/payer/ioitalia/aosta/include/ioitaliaconfEdit.jsp" />
	   	<parameter key="footer" value="/applications/templates/shared/aosta/footer.jsp"/>
	  </screen>
	  
	  <screen name="ioitalianewmessage" template="default">
	    <parameter key="pagetitle" value="manager.ioitalia.search.title" direct="true" />
	  	<parameter key="header" value="/applications/templates/shared/aosta/header.jsp"/>
	    <parameter key="menu" value="/applications/templates/shared/menu.jsp" />
	    <parameter key="main" value="/applications/payer/ioitalia/aosta/include/ioitalianew.jsp" />
	   	<parameter key="footer" value="/applications/templates/shared/aosta/footer.jsp"/>
	  </screen>
	  
	  <screen name="ioitaliamessageedit" template="default">
	    <parameter key="pagetitle" value="manager.ioitalia.search.title" direct="true" />
	  	<parameter key="header" value="/applications/templates/shared/aosta/header.jsp"/>
	    <parameter key="menu" value="/applications/templates/shared/menu.jsp" />
	    <parameter key="main" value="/applications/payer/ioitalia/aosta/include/ioitaliamessageedit.jsp" />
	   	<parameter key="footer" value="/applications/templates/shared/aosta/footer.jsp"/>
	  </screen>
	  
	  <screen name="ioitaliaupload" template="default">
	    <parameter key="pagetitle" value="manager.ioitalia.upload.title" direct="true" />
	  	<parameter key="header" value="/applications/templates/shared/aosta/header.jsp"/>
	    <parameter key="menu" value="/applications/templates/shared/menu.jsp" />
	    <parameter key="main" value="/applications/payer/ioitalia/aosta/include/ioitaliacaricaCsv.jsp" />
	   	<parameter key="footer" value="/applications/templates/shared/aosta/footer.jsp"/>
	  </screen> 
	  
  </templates>
