=== regione-marche/org.seda.payer.manager.web/WebContent/WEB-INF/xsd/maf-templates.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
targetNamespace="http://template.core.maf.j2ee5.seda.com"
xmlns="http://template.core.maf.j2ee5.seda.com"
elementFormDefault="qualified">

<xsd:annotation>
 	<xsd:documentation xml:lang="en">
    </xsd:documentation>
</xsd:annotation>


<xsd:element name="templates" type="templatesType"/>

<xsd:complexType name="templatesType">
	<xsd:sequence>
		<xsd:element name="default" type="xsd:string" minOccurs="1" maxOccurs="1"/>	
		<xsd:element name="bundle" type="xsd:string" minOccurs="0" maxOccurs="1"/>		
		<xsd:element name="template" type="templateType"  minOccurs="0" maxOccurs="unbounded"/>		
		<xsd:element name="screen" type="screenType"  minOccurs="0" maxOccurs="unbounded"/>
    </xsd:sequence>
</xsd:complexType>

<xsd:complexType name="templateType">
	<xsd:sequence>
		<xsd:element name="url" type="xsd:string" minOccurs="1" maxOccurs="1"/>	
    </xsd:sequence>
    <xsd:attribute name="name" type="xsd:string" use="required"/>
        
</xsd:complexType>

<xsd:complexType name="screenType">
	<xsd:sequence>
		<xsd:element name="parameter" type="parameterType" minOccurs="1" maxOccurs="unbounded"/>	
    </xsd:sequence>
    <xsd:attribute name="name" type="xsd:string" use="required"/>    
    <xsd:attribute name="template" type="xsd:string"/>
    <xsd:attribute name="menuaction" type="xsd:string"/>        
</xsd:complexType>

<xsd:complexType name="parameterType">
    <xsd:attribute name="key" type="xsd:string" use="required"/>    
    <xsd:attribute name="value" type="xsd:string" use="required"/>    
    <xsd:attribute name="direct" type="xsd:string"/>    
	<xsd:attribute name="args" type="xsd:string"/>    
</xsd:complexType>

</xsd:schema>

=== regione-marche/org.seda.payer.manager.web/WebContent/applications/payer/monitoraggio/maf-templates-padanatech.xml
<?xml version="1.0" encoding="UTF-8"?>
<templates xmlns="http://template.core.maf.j2ee5.seda.com"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://template.core.maf.j2ee5.seda.com ./../WEB-INF/xsd/maf-templates.xsd">

  <default>/applications/templates/default/default.jsp</default>

  <bundle>org.seda.payer.manager.resources.TemplateStrings</bundle>

  <template name="defaultUTF8">
		<url>/applications/templates/default/defaultUTF8.jsp</url>
  </template>
  
  <screen name="monitoraggioTransazioni" template="defaultUTF8">
    <parameter key="pagetitle" value="title.monitoraggio" direct="true" />
  	<parameter key="header" value="/applications/templates/shared/padanatech/header.jsp"/>
  	<parameter key="menu" value="/applications/templates/shared/menu.jsp" />
    <parameter key="main" value="/applications/payer/monitoraggio/padanatech/MonitoraggioTransazioni.jsp" />
    <parameter key="main2" value="/applications/payer/monitoraggio/padanatech/PopupDettaglioTransazione.jsp" />
  	<parameter key="footer" value="/applications/templates/shared/padanatech/footer.jsp"/>
  </screen>

  <screen name="modificaEmailSms" template="default">
    <parameter key="pagetitle" value="title.monitoraggio" direct="true" />
  	<parameter key="header" value="/applications/templates/shared/padanatech/header.jsp"/>
  	<parameter key="menu" value="/applications/templates/shared/menu.jsp" />
    <parameter key="main" value="/applications/payer/monitoraggio/padanatech/ModificaEmailSMSUtente.jsp" />
  	<parameter key="footer" value="/applications/templates/shared/padanatech/footer.jsp"/>
  </screen>

  <screen name="dettaglioTransazione" template="defaultUTF8">
    <parameter key="pagetitle" value="title.monitoraggio" direct="true" />
  	<parameter key="header" value="/applications/templates/shared/padanatech/header.jsp"/>
  	<parameter key="menu" value="/applications/templates/shared/menu.jsp" />
    <parameter key="main" value="/applications/payer/monitoraggio/padanatech/DettaglioTransazione.jsp" />
    <parameter key="main2" value="/applications/payer/monitoraggio/padanatech/ButtonDettaglioTransazione.jsp" />
  	<parameter key="footer" value="/applications/templates/shared/padanatech/footer.jsp"/>
  </screen>

  <screen name="forzaAllineamentoTransazione" template="default">
    <parameter key="pagetitle" value="title.monitoraggio" direct="true" />
  	<parameter key="header" value="/applications/templates/shared/padanatech/header.jsp"/>
  	<parameter key="menu" value="/applications/templates/shared/menu.jsp" />
    <parameter key="main" value="/applications/payer/monitoraggio/padanatech/ForzaAllineamentoTransazione.jsp" />
  	<parameter key="footer" value="/applications/templates/shared/padanatech/footer.jsp"/>
  </screen>
 
 <screen name="allineaManualmenteTransazione" template="default">
    <parameter key="pagetitle" value="title.monitoraggio" direct="true" />
  	<parameter key="header" value="/applications/templates/shared/padanatech/header.jsp"/>
  	<parameter key="menu" value="/applications/templates/shared/menu.jsp" />
    <parameter key="main" value="/applications/payer/monitoraggio/padanatech/AllineaManualmenteTransazione.jsp" />
  	<parameter key="footer" value="/applications/templates/shared/padanatech/footer.jsp"/>
  </screen> 
  
  <screen name="inviaNotificaAmministratore" template="default">
    <parameter key="pagetitle" value="title.monitoraggio" direct="true" />
  	<parameter key="header" value="/applications/templates/shared/padanatech/header.jsp"/>
  	<parameter key="menu" value="/applications/templates/shared/menu.jsp" />
    <parameter key="main" value="/applications/payer/monitoraggio/padanatech/InviaNotificaAmministratore.jsp" />
  	<parameter key="footer" value="/applications/templates/shared/padanatech/footer.jsp"/>
  </screen>
  
  <screen name="inviaNotificaContribuente" template="default">
    <parameter key="pagetitle" value="title.monitoraggio" direct="true"/>
  	<parameter key="header" value="/applications/templates/shared/padanatech/header.jsp"/>
  	<parameter key="menu" value="/applications/templates/shared/menu.jsp" />
    <parameter key="main" value="/applications/payer/monitoraggio/padanatech/InviaNotificaContribuente.jsp" />
  	<parameter key="footer" value="/applications/templates/shared/padanatech/footer.jsp"/>
  </screen>
  <!--<screen name="scaricaReportCSV" template="default">
    <parameter key="pagetitle" value="title.monitoraggio" direct="true" />
  	<parameter key="header" value="/applications/templates/shared/padanatech/header.jsp"/>
    <parameter key="main" value="/applications/payer/monitoraggio/padanatech/ScaricaReportCSV.jsp" />
  	<parameter key="footer" value="/applications/templates/shared/padanatech/footer.jsp"/>
  </screen>-->
  
  <screen name="stampaPDFBollettini" template="default">
    <parameter key="pagetitle" value="title.monitoraggio" direct="true" />
  	<parameter key="header" value="/applications/templates/shared/padanatech/header.jsp"/>
  	<parameter key="menu" value="/applications/templates/shared/menu.jsp" />
    <parameter key="main" value="/applications/payer/monitoraggio/padanatech/StampaPDFBollettini.jsp" />
  	<parameter key="footer" value="/applications/templates/shared/padanatech/footer.jsp"/>
  </screen>
 
  
  <!--<screen name="stampaReportPDF" template="default">
    <parameter key="pagetitle" value="title.monitoraggio" direct="true" />
  	<parameter key="header" value="/applications/templates/shared/padanatech/header.jsp"/>
    <parameter key="main" value="/applications/payer/monitoraggio/padanatech/StampaReportPDF.jsp" />
  	<parameter key="footer" value="/applications/templates/shared/padanatech/footer.jsp"/>
  </screen>-->
  
  <screen name="richiediRiconciliazione" template="default">
    <parameter key="pagetitle" value="title.monitoraggio" direct="true" />
  	<parameter key="header" value="/applications/templates/shared/padanatech/header.jsp"/>
  	<parameter key="menu" value="/applications/templates/shared/menu.jsp" />
    <parameter key="main" value="/applications/payer/monitoraggio/padanatech/RichiediRiconciliazione.jsp" />
  	<parameter key="footer" value="/applications/templates/shared/padanatech/footer.jsp"/>
  </screen>
  
</templates>

=== regione-marche/org.seda.payer.manager.web/WebContent/applications/payer/entrate/maf-templates-padanatech.xml
<?xml version="1.0" encoding="UTF-8"?>
<templates xmlns="http://template.core.maf.j2ee5.seda.com"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://template.core.maf.j2ee5.seda.com ./../WEB-INF/xsd/maf-templates.xsd">

  <default>/applications/templates/default/default.jsp</default>

  <bundle>org.seda.payer.manager.resources.TemplateStrings</bundle>

 <screen name="ricercaAnagrafiche" template="default">
    <parameter key="pagetitle" value="title.entrate.anagrafiche" direct="true"/>
  	<parameter key="header" value="/applications/templates/shared/padanatech/header.jsp"/>
  	<parameter key="menu" value="/applications/templates/shared/menu.jsp" />
    <parameter key="main" value="/applications/payer/entrate/include/RicercaAnag.jsp" />
  	<parameter key="footer" value="/applications/templates/shared/padanatech/footer.jsp"/>
  </screen>

 <screen name="ricercaDocumentiAnag" template="default">
    <parameter key="pagetitle" value="title.entrate.anagrafiche" direct="true"/>
  	<parameter key="header" value="/applications/templates/shared/padanatech/header.jsp"/>
  	<parameter key="menu" value="/applications/templates/shared/menu.jsp" />
    <parameter key="main" value="/applications/payer/entrate/include/DocumentiAnag.jsp" />
  	<parameter key="footer" value="/applications/templates/shared/padanatech/footer.jsp"/>
  </screen>


 <screen name="ricercaEmissioni" template="default">
    <parameter key="pagetitle" value="title.entrate.emissioni" direct="true"/>
  	<parameter key="header" value="/applications/templates/shared/padanatech/header.jsp"/>
  	<parameter key="menu" value="/applications/templates/shared/menu.jsp" />
    <parameter key="main" value="/applications/payer/entrate/include/RicercaEmissioni.jsp" />
  	<parameter key="footer" value="/applications/templates/shared/padanatech/footer.jsp"/>
  </screen>

  <screen name="dettaglioEmissione" template="default">
    <parameter key="pagetitle" value="title.entrate.emissioni" direct="true"/>
  	<parameter key="header" value="/applications/templates/shared/padanatech/header.jsp"/>
  	<parameter key="menu" value="/applications/templates/shared/menu.jsp" />
    <parameter key="main" value="/applications/payer/entrate/include/dettaglioEmissione.jsp" />
  	<parameter key="footer" value="/applications/templates/shared/padanatech/footer.jsp"/>
  </screen>

 <screen name="ricercaDocumentiEmi" template="default">
    <parameter key="pagetitle" value="title.entrate.emissioni" direct="true"/>
  	<parameter key="header" value="/applications/templates/shared/padanatech/header.jsp"/>
  	<parameter key="menu" value="/applications/templates/shared/menu.jsp" />
    <parameter key="main" value="/applications/payer/entrate/include/DocumentiEmissione.jsp" />
  	<parameter key="footer" value="/applications/templates/shared/padanatech/footer.jsp"/>
  </screen>


 <screen name="ricercaDocumenti" template="default">
    <parameter key="pagetitle" value="title.entrate.documenti" direct="true"/>
  	<parameter key="header" value="/applications/templates/shared/padanatech/header.jsp"/>
  	<parameter key="menu" value="/applications/templates/shared/menu.jsp" />
    <parameter key="main" value="/applications/payer/entrate/include/ricercaDocumentiCarichi.jsp" />
  	<parameter key="footer" value="/applications/templates/shared/padanatech/footer.jsp"/>
  </screen>

  <screen name="documentoDettaglio" template="default">
    <parameter key="pagetitle" value="title.entrate.documenti" direct="true"/>
  	<parameter key="header" value="/applications/templates/shared/padanatech/header.jsp"/>
  	<parameter key="menu" value="/applications/templates/shared/menu.jsp" />
    <parameter key="main" value="/applications/payer/entrate/include/DettaglioDocumento.jsp" />
  	<parameter key="footer" value="/applications/templates/shared/padanatech/footer.jsp"/>
  </screen>

 <screen name="ricercaPagamenti" template="default">
    <parameter key="pagetitle" value="title.entrate.pagamenti" direct="true"/>
  	<parameter key="header" value="/applications/templates/shared/padanatech/header.jsp"/>
  	<parameter key="menu" value="/applications/templates/shared/menu.jsp" />
    <parameter key="main" value="/applications/payer/entrate/include/RicercaPagamenti.jsp" />
  	<parameter key="footer" value="/applications/templates/shared/padanatech/footer.jsp"/>
  </screen>
  
   <screen name="listaTributi" template="default">
    <parameter key="pagetitle" value="title.entrate.tributi" direct="true"/>
  	<parameter key="header" value="/applications/templates/shared/padanatech/header.jsp"/>
  	<parameter key="menu" value="/applications/templates/shared/menu.jsp" />
    <parameter key="main" value="/applications/payer/entrate/include/listaTributi.jsp" />
  	<parameter key="footer" value="/applications/templates/shared/padanatech/footer.jsp"/>
  </screen>
  
   <screen name="listaScadenze" template="default">
    <parameter key="pagetitle" value="title.entrate.scadenze" direct="true"/>
  	<parameter key="header" value="/applications/templates/shared/padanatech/header.jsp"/>
  	<parameter key="menu" value="/applications/templates/shared/menu.jsp" />
    <parameter key="main" value="/applications/payer/entrate/include/listaScadenze.jsp" />
  	<parameter key="footer" value="/applications/templates/shared/padanatech/footer.jsp"/>
  </screen>

   <screen name="listaPagamenti" template="default">
    <parameter key="pagetitle" value="title.entrate.pagamenti" direct="true"/>
  	<parameter key="header" value="/applications/templates/shared/padanatech/header.jsp"/>
  	<parameter key="menu" value="/applications/templates/shared/menu.jsp" />
    <parameter key="main" value="/applications/payer/entrate/include/listaPagamenti.jsp" />
  	<parameter key="footer" value="/applications/templates/shared/padanatech/footer.jsp"/>
  </screen>
 
   <screen name="ricercaNote" template="default">
    <parameter key="pagetitle" value="title.entrate.note" direct="true"/>
  	<parameter key="header" value="/applications/templates/shared/padanatech/header.jsp"/>
  	<parameter key="menu" value="/applications/templates/shared/menu.jsp" />
    <parameter key="main" value="/applications/payer/entrate/include/listaNote.jsp" />
  	<parameter key="footer" value="/applications/templates/shared/padanatech/footer.jsp"/>
  </screen>

</templates>

=== regione-marche/org.seda.payer.manager.web/WebContent/applications/payer/monitoraggiowis/maf-templates-sap.xml
<?xml version="1.0" encoding="UTF-8"?>
<templates xmlns="http://template.core.maf.j2ee5.seda.com"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://template.core.maf.j2ee5.seda.com ./../WEB-INF/xsd/maf-templates.xsd">

  <default>/applications/templates/default/default.jsp</default>
  
  <bundle>org.seda.payer.manager.resources.TemplateStrings</bundle>

  <screen name="monitoraggiowis" template="default">
    <parameter key="pagetitle" value="title.monitoraggiowis" direct="true"/>
  	<parameter key="header" value="/applications/templates/shared/sap/header.jsp"/>
    <parameter key="menu" value="/applications/templates/shared/menu.jsp" />
    <parameter key="main" value="/applications/payer/monitoraggiowis/include/monitoraggiowis.jsp" />
  	<parameter key="footer" value="/applications/templates/shared/sap/footer.jsp"/>
  </screen>
  
  <screen name="dettagliocomunicazione" template="default">
    <parameter key="pagetitle" value="title.monitoraggiowis" direct="true"/>
  	<parameter key="header" value="/applications/templates/shared/sap/header.jsp"/>
    <parameter key="menu" value="/applications/templates/shared/menu.jsp" />
    <parameter key="main" value="/applications/payer/monitoraggiowis/include/dettagliocomunicazione.jsp" />
  	<parameter key="footer" value="/applications/templates/shared/sap/footer.jsp"/>
  </screen>

  
</templates>

=== regione-marche/org.seda.payer.manager.web/WebContent/applications/payer/blackboxconfig/maf-templates-aosta.xml
<?xml version="1.0" encoding="UTF-8"?>
<templates xmlns="http://template.core.maf.j2ee5.seda.com"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://template.core.maf.j2ee5.seda.com ../../../WEB-INF/xsd/maf-templates.xsd">

	  <default>/applications/templates/default/default.jsp</default>
	
	  <bundle>org.seda.payer.manager.resources.TemplateStrings</bundle>
	  
	  <template name="errori">
		<url>/applications/templates/default/error_template.jsp</url>
	  </template>
	
	  <screen name="blackbox" template="default">
	    <parameter key="pagetitle" value="manager.blackbox.search.title" direct="true" />
	  	<parameter key="header" value="/applications/templates/shared/aosta/header.jsp"/>
	    <parameter key="menu" value="/applications/templates/shared/menu.jsp" />
	    <parameter key="main" value="/applications/payer/blackboxconfig/aosta/include/blackBox.jsp" /> <!-- LP PG200420 - 20210423 -->
	   <parameter key="footer" value="/applications/templates/shared/aosta/footer.jsp"/>
	  </screen>
	   <screen name="blackboxEdit" template="default">
	    <parameter key="pagetitle" value="manager.blackbox.search.title" direct="true" />
	  	<parameter key="header" value="/applications/templates/shared/aosta/header.jsp"/>
	    <parameter key="menu" value="/applications/templates/shared/menu.jsp" />
	    <parameter key="main" value="/applications/payer/blackboxconfig/aosta/include/blackBoxEdit.jsp" /> <!-- LP PG200420 - 20210423 -->
	    <parameter key="footer" value="/applications/templates/shared/aosta/footer.jsp"/>
	  </screen>
	  <screen name="blackboxCancel" template="default">
	    <parameter key="pagetitle" value="manager.blackbox.search.title" direct="true" />
	  	<parameter key="header" value="/applications/templates/shared/aosta/header.jsp"/>
	    <parameter key="menu" value="/applications/templates/shared/menu.jsp" />
	    <parameter key="main" value="/applications/payer/blackboxconfig/include/blackbox_cancel.jsp" />
	    <parameter key="footer" value="/applications/templates/shared/aosta/footer.jsp"/>
	  </screen>
	  

  </templates>

=== regione-marche/org.seda.payer.manager.web/WebContent/applications/payer/monitoraggio/maf-templates-fccsa.xml
<?xml version="1.0" encoding="UTF-8"?>
<templates xmlns="http://template.core.maf.j2ee5.seda.com"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://template.core.maf.j2ee5.seda.com ./../WEB-INF/xsd/maf-templates.xsd">

  <default>/applications/templates/default/default.jsp</default>

  <bundle>org.seda.payer.manager.resources.TemplateStrings</bundle>

  <template name="defaultUTF8">
		<url>/applications/templates/default/defaultUTF8.jsp</url>
  </template>
  
  <screen name="monitoraggioTransazioni" template="defaultUTF8">
    <parameter key="pagetitle" value="title.monitoraggio" direct="true" />
  	<parameter key="header" value="/applications/templates/shared/fccsa/header.jsp"/>
  	<parameter key="menu" value="/applications/templates/shared/menu.jsp" />
    <parameter key="main" value="/applications/payer/monitoraggio/fccsa/MonitoraggioTransazioni.jsp" />
    <parameter key="main2" value="/applications/payer/monitoraggio/fccsa/PopupDettaglioTransazione.jsp" />
  	<parameter key="footer" value="/applications/templates/shared/fccsa/footer.jsp"/>
  </screen>

  <screen name="modificaEmailSms" template="default">
    <parameter key="pagetitle" value="title.monitoraggio" direct="true" />
  	<parameter key="header" value="/applications/templates/shared/fccsa/header.jsp"/>
  	<parameter key="menu" value="/applications/templates/shared/menu.jsp" />
    <parameter key="main" value="/applications/payer/monitoraggio/fccsa/ModificaEmailSMSUtente.jsp" />
  	<parameter key="footer" value="/applications/templates/shared/fccsa/footer.jsp"/>
  </screen>

  <screen name="dettaglioTransazione" template="defaultUTF8">
    <parameter key="pagetitle" value="title.monitoraggio" direct="true" />
  	<parameter key="header" value="/applications/templates/shared/fccsa/header.jsp"/>
  	<parameter key="menu" value="/applications/templates/shared/menu.jsp" />
    <parameter key="main" value="/applications/payer/monitoraggio/fccsa/DettaglioTransazione.jsp" />
    <parameter key="main2" value="/applications/payer/monitoraggio/fccsa/ButtonDettaglioTransazione.jsp" />
  	<parameter key="footer" value="/applications/templates/shared/fccsa/footer.jsp"/>
  </screen>

  <screen name="forzaAllineamentoTransazione" template="default">
    <parameter key="pagetitle" value="title.monitoraggio" direct="true" />
  	<parameter key="header" value="/applications/templates/shared/fccsa/header.jsp"/>
  	<parameter key="menu" value="/applications/templates/shared/menu.jsp" />
    <parameter key="main" value="/applications/payer/monitoraggio/fccsa/ForzaAllineamentoTransazione.jsp" />
  	<parameter key="footer" value="/applications/templates/shared/fccsa/footer.jsp"/>
  </screen>
 
 <screen name="allineaManualmenteTransazione" template="default">
    <parameter key="pagetitle" value="title.monitoraggio" direct="true" />
  	<parameter key="header" value="/applications/templates/shared/fccsa/header.jsp"/>
  	<parameter key="menu" value="/applications/templates/shared/menu.jsp" />
    <parameter key="main" value="/applications/payer/monitoraggio/fccsa/AllineaManualmenteTransazione.jsp" />
  	<parameter key="footer" value="/applications/templates/shared/fccsa/footer.jsp"/>
  </screen> 
  
  <screen name="inviaNotificaAmministratore" template="default">
    <parameter key="pagetitle" value="title.monitoraggio" direct="true" />
  	<parameter key="header" value="/applications/templates/shared/fccsa/header.jsp"/>
  	<parameter key="menu" value="/applications/templates/shared/menu.jsp" />
    <parameter key="main" value="/applications/payer/monitoraggio/fccsa/InviaNotificaAmministratore.jsp" />
  	<parameter key="footer" value="/applications/templates/shared/fccsa/footer.jsp"/>
  </screen>
  
  <screen name="inviaNotificaContribuente" template="default">
    <parameter key="pagetitle" value="title.monitoraggio" direct="true"/>
  	<parameter key="header" value="/applications/templates/shared/fccsa/header.jsp"/>
  	<parameter key="menu" value="/applications/templates/shared/menu.jsp" />
    <parameter key="main" value="/applications/payer/monitoraggio/fccsa/InviaNotificaContribuente.jsp" />
  	<parameter key="footer" value="/applications/templates/shared/fccsa/footer.jsp"/>
  </screen>
  <!--<screen name="scaricaReportCSV" template="default">
    <parameter key="pagetitle" value="title.monitoraggio" direct="true" />
  	<parameter key="header" value="/applications/templates/shared/fccsa/header.jsp"/>
    <parameter key="main" value="/applications/payer/monitoraggio/fccsa/ScaricaReportCSV.jsp" />
  	<parameter key="footer" value="/applications/templates/shared/fccsa/footer.jsp"/>
  </screen>-->
  
  <screen name="stampaPDFBollettini" template="default">
    <parameter key="pagetitle" value="title.monitoraggio" direct="true" />
  	<parameter key="header" value="/applications/templates/shared/fccsa/header.jsp"/>
  	<parameter key="menu" value="/applications/templates/shared/menu.jsp" />
    <parameter key="main" value="/applications/payer/monitoraggio/fccsa/StampaPDFBollettini.jsp" />
  	<parameter key="footer" value="/applications/templates/shared/fccsa/footer.jsp"/>
  </screen>
 
  
  <!--<screen name="stampaReportPDF" template="default">
    <parameter key="pagetitle" value="title.monitoraggio" direct="true" />
  	<parameter key="header" value="/applications/templates/shared/fccsa/header.jsp"/>
    <parameter key="main" value="/applications/payer/monitoraggio/fccsa/StampaReportPDF.jsp" />
  	<parameter key="footer" value="/applications/templates/shared/fccsa/footer.jsp"/>
  </screen>-->
  
  <screen name="richiediRiconciliazione" template="default">
    <parameter key="pagetitle" value="title.monitoraggio" direct="true" />
  	<parameter key="header" value="/applications/templates/shared/fccsa/header.jsp"/>
  	<parameter key="menu" value="/applications/templates/shared/menu.jsp" />
    <parameter key="main" value="/applications/payer/monitoraggio/fccsa/RichiediRiconciliazione.jsp" />
  	<parameter key="footer" value="/applications/templates/shared/fccsa/footer.jsp"/>
  </screen>
  
</templates>
