=== regione-marche/org.seda.payer.manager.web/WebContent/WEB-INF/xsd/maf-actions.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
targetNamespace="http://action.core.maf.j2ee5.seda.com"
xmlns="http://action.core.maf.j2ee5.seda.com"
elementFormDefault="qualified">
 
<xsd:annotation>
 	<xsd:documentation xml:lang="en">
    </xsd:documentation>
</xsd:annotation>

<xsd:element name="actions-mapping" type="actionsMappingType"/>
  
<xsd:complexType name="actionsMappingType">
	<xsd:sequence>
		<xsd:element name="menu" type="menuType" minOccurs="0" maxOccurs="1"/>
		<xsd:element name="complex-actions" type="complexType" minOccurs="0" maxOccurs="1"/>
		<xsd:element name="global-ruleset" type="globalRulesetType" minOccurs="0" maxOccurs="1"/>
		<xsd:element name="action" type="actionType" minOccurs="0" maxOccurs="unbounded"/>
    </xsd:sequence>
</xsd:complexType>

<xsd:complexType name="menuType">
	<xsd:sequence>
		<xsd:element name="link" type="menuLinkType" minOccurs="1" maxOccurs="unbounded"/>	
    </xsd:sequence>    
</xsd:complexType>

<xsd:complexType name="menuLinkType">
	<xsd:attribute name="text" type="xsd:string" use="required"/>	
	<xsd:attribute name="actionurl" type="xsd:string" use="required"/>
	<xsd:attribute name="enabled" type="xsd:boolean" use="optional"/>
</xsd:complexType>

<xsd:complexType name="complexType">
	<xsd:sequence>
		<xsd:element name="complex-target" type="complexTargetType" minOccurs="1" maxOccurs="unbounded"/>	
    </xsd:sequence>    
</xsd:complexType>

<xsd:complexType name="complexTargetType">
	<xsd:attribute name="value" type="xsd:string" use="required"/>	
	<xsd:attribute name="actionurl" type="xsd:string" use="required"/>
</xsd:complexType>

<xsd:complexType name="globalRulesetType">
	<xsd:sequence>
		<xsd:element name="regexset" type="regexsetType" minOccurs="0" maxOccurs="unbounded"/>	
		<xsd:element name="ruleset" type="rulesetType" minOccurs="0" maxOccurs="unbounded"/>
    </xsd:sequence>
</xsd:complexType>

<xsd:complexType name="regexsetType">
	<xsd:sequence>
		<xsd:element name="regex" type="regexType" minOccurs="1" maxOccurs="unbounded"/>
	</xsd:sequence>
</xsd:complexType>

<xsd:complexType name="regexType">
	<xsd:sequence>
		<xsd:element name="pattern" type="xsd:string" minOccurs="1" maxOccurs="1"/>
		<xsd:element name="description" type="xsd:string" minOccurs="1" maxOccurs="1"/>
	</xsd:sequence>
	<xsd:attribute name="name" type="xsd:string" use="required"/>	
</xsd:complexType>

<xsd:complexType name="rulesetType">
	<xsd:sequence>
		<xsd:element name="rule" type="ruleType" minOccurs="0" maxOccurs="unbounded"/>
	</xsd:sequence>
</xsd:complexType>

<xsd:complexType name="ruleType">
	<xsd:sequence>
		<xsd:element name="validation" type="xsd:string" minOccurs="0" maxOccurs="1"/>
		<xsd:element name="missing" type="ruleCategoryType" minOccurs="1" maxOccurs="1"/>
		<xsd:element name="malformed" type="ruleCategoryType" minOccurs="1" maxOccurs="1"/>
	</xsd:sequence>
	<xsd:attribute name="name" type="xsd:string" use="required"/>
	<xsd:attribute name="regex" type="xsd:string"/>
</xsd:complexType>

<xsd:complexType name="ruleCategoryType">
	<xsd:sequence>
		<xsd:element name="rule-action" type="ruleActionType" minOccurs="0" maxOccurs="unbounded"/>
	</xsd:sequence>
	<xsd:attribute name="severity" use="required">
		<xsd:simpleType>
			<xsd:restriction base="xsd:string">
				<!-- xsd:enumeration value="ignore"/ -->
				<xsd:enumeration value="continue"/>				
				<xsd:enumeration value="fatal"/>
			</xsd:restriction>
		</xsd:simpleType>
	</xsd:attribute>
</xsd:complexType>

<xsd:complexType name="ruleActionType">
	<xsd:sequence>
		<xsd:element name="parameter" type="ruleActionParameterType" minOccurs="0" maxOccurs="unbounded"/>
	</xsd:sequence>
	<xsd:attribute name="class" use="required"/>
</xsd:complexType>

<xsd:complexType name="ruleActionParameterType">
	<xsd:attribute  name="name" type="xsd:string" use="required"/>
	<xsd:attribute  name="value" type="xsd:string" use="required"/>
</xsd:complexType>

<xsd:complexType name="actionType">
	<xsd:sequence>
		<xsd:element name="role-collection" type="actionRoleType" minOccurs="0" maxOccurs="1"/>
		<xsd:element name="description" type="xsd:string" minOccurs="0" maxOccurs="1"/>			
		<xsd:element name="action-class" type="xsd:string"/>
		<xsd:element name="flow" type="flowType" minOccurs="0" maxOccurs="1"/>
		<xsd:element name="writer" type="writerType" minOccurs="0" maxOccurs="1"/>
		<xsd:element name="redirect" type="redirectType" minOccurs="0" maxOccurs="1"/>
		<xsd:element name="settings" type="settingsType" minOccurs="0" maxOccurs="1"/>				
		<xsd:element name="ruleset" type="rulesetType" minOccurs="0" maxOccurs="1"/>		
    </xsd:sequence>
    <xsd:attribute name="url" type="xsd:string" use="required"/>
    <xsd:attribute name="menuaction" type="xsd:string"/>    
    <xsd:attribute name="screen" type="xsd:string" />
    <xsd:attribute name="flow" type="xsd:boolean" />    
    <xsd:attribute name="writer" type="xsd:boolean" />    
    <xsd:attribute name="redirect" type="xsd:boolean" />    
    <xsd:attribute name="csrf" type="xsd:boolean" />    
</xsd:complexType>

<xsd:complexType name="actionRoleType">
	<xsd:sequence>
		<xsd:element name="role" type="xsd:string" minOccurs="1" maxOccurs="unbounded"/>	
    </xsd:sequence>    	
</xsd:complexType>

<xsd:complexType name="flowType">
	<xsd:sequence>
		<xsd:element name="settings" type="settingsType" minOccurs="0" maxOccurs="1"/>
		<xsd:element name="properties" type="propertiesType" minOccurs="0" maxOccurs="1"/>	
		<xsd:element name="result" type="resultType" minOccurs="1" maxOccurs="unbounded"/>
    </xsd:sequence>
    <xsd:attribute name="class" type="xsd:string" use="required"/>
</xsd:complexType>

<xsd:complexType name="resultType">
    <xsd:attribute name="value" type="xsd:string" use="required"/>
    <xsd:attribute name="screen" type="xsd:string"/>
    <xsd:attribute name="applid" type="xsd:string"/>
    <xsd:attribute name="writer" type="xsd:string"/>    
    <xsd:attribute name="redirect" type="xsd:string"/>
    <xsd:attribute name="inScope" type="xsd:boolean"/>
	<xsd:attribute name="content-type" type="xsd:string"/>    
	<xsd:attribute name="attach" type="xsd:string"/>
</xsd:complexType>

<xsd:complexType name="writerType">
    <xsd:attribute name="id" type="xsd:string" use="required"/>
	<xsd:attribute name="attach" type="xsd:string"/>    
	<xsd:attribute name="scope">
		<xsd:simpleType>
			<xsd:restriction base="xsd:string">
				<xsd:enumeration value="application"/>
				<xsd:enumeration value="session"/>				
				<xsd:enumeration value="request"/>
			</xsd:restriction>
		</xsd:simpleType>
	</xsd:attribute>
	<xsd:attribute name="inScope" type="xsd:boolean"/>
	<xsd:attribute name="content-type" type="xsd:string" use="required"/>
</xsd:complexType>

<xsd:complexType name="redirectType">
    <xsd:attribute name="id" type="xsd:string"/>
	<xsd:attribute name="url" type="xsd:string"/>    
</xsd:complexType>  

<xsd:complexType name="settingsType">
	<xsd:sequence>
		<xsd:element name="property" type="propertyType" minOccurs="1" maxOccurs="unbounded"/>
    </xsd:sequence>    
</xsd:complexType>

<xsd:complexType name="propertiesType">
	<xsd:sequence>
		<xsd:element name="property" type="propertyType" minOccurs="1" maxOccurs="unbounded"/>
    </xsd:sequence>    
</xsd:complexType>    

<xsd:complexType name="propertyType">
    <xsd:attribute name="key" type="xsd:string" use="required"/>
	<xsd:attribute name="value" type="xsd:string" use="required"/>    
</xsd:complexType>  
  
</xsd:schema>

=== regione-marche/org.seda.payer.manager.web/WebContent/applications/payer/login/maf-actions.xml
<?xml version="1.0" encoding="UTF-8"?>

<actions-mapping xmlns="http://action.core.maf.j2ee5.seda.com"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://action.core.maf.j2ee5.seda.com ../../../WEB-INF/xsd/maf-actions.xsd">
	 
	<global-ruleset>
 		<regexset>
 			<regex name="username_regex">
 				<pattern>^[a-zA-Z0-9].{3,50}$</pattern>
 				<description></description>
 			</regex>
 			<regex name="vecchia_password_regex">
 				<pattern>^.{8,15}$</pattern>
 				<description></description>
 			</regex>
 			<regex name="password_regex">
 				<pattern>^[a-zA-Z0-9\.,!#%]{8,15}$</pattern>
 				<description></description>
 			</regex>
 			<regex name="puk_regex">
 				<pattern>^.{5,256}$</pattern>
 				<description></description>
 			</regex>
 			<regex name="email_regex">
 				<pattern><![CDATA[^[\w\-\+\&\*]+(?:\.[\w\-\_\+\&\*]+)*@(?:[a-zA-Z0-9\-]+\.)+[a-zA-Z]{2,7}$]]></pattern>
 				<description></description>
 			</regex>
 		</regexset>
 	</global-ruleset>
	 
	<action  url="login.do" screen="login.screen">
       <action-class>org.seda.payer.manager.actions.SignOnAction</action-class>
    </action>
    
    <action  url="loginPdp.do" screen="login_pdp.screen">
       <action-class>org.seda.payer.manager.actions.SignOnAction</action-class>
    </action>
    
 	<action url="logoff.do" screen="login.do" flow="true">
        <action-class>org.seda.payer.manager.actions.ActionCaller</action-class>
        <flow  class="org.seda.payer.manager.actions.LoginFlowAction" >
        	<result value="redirect" redirect="urlPortale"/>
			<result value="login" screen="login.do"/>
        </flow>
    </action>
    
    <action url="logoffAuthFederata.do" screen="login.do" >
        <action-class>org.seda.payer.manager.login.trentrisc.actions.SignOffAction</action-class>
    </action>
    
    <action url="logoffAuthFederataBolzano.do" screen="login.do" >
        <action-class>org.seda.payer.manager.login.bolzano.actions.SignOffAction</action-class>
    </action>
        
    <!-- inizio LP PG200060 -->
    <action url="logoffAuthFederataRegMarche.do" screen="login.do" >
        <action-class>org.seda.payer.manager.login.regmarche.actions.SignOffAction</action-class>
    </action>
    <!-- fine LP PG200060 -->

	<action url="resetPswd.do" screen="resetpswd.screen" flow="true">
        <action-class>org.seda.payer.manager.login.actions.ResetPswdAction</action-class>
		<flow  class="org.seda.payer.manager.login.actions.ResetPswdFlowAction" >
			<result value="resetPswd" screen="resetpswd.screen"/>
			<result value="login" screen="login.screen"/>
		</flow>
        <ruleset>
			<rule name="tx_username" regex="username_regex">
        		<missing severity="continue"/>
        		<malformed severity="continue"><rule-action class="com.seda.j2ee5.maf.defender.action.impl.Blank"/></malformed>
        	</rule>
			<rule name="puk" regex="puk_regex">
        		<missing severity="continue"/>
        		<malformed severity="continue"><rule-action class="com.seda.j2ee5.maf.defender.action.impl.Blank"/></malformed>
        	</rule>
			<rule name="emailNotifiche" regex="email_regex">
        		<missing severity="continue"/>
        		<malformed severity="continue"><rule-action class="com.seda.j2ee5.maf.defender.action.impl.Blank"/></malformed>
        	</rule>
		</ruleset>
    </action>
    
    	<action url="cambioPswd.do" screen="cambiopswd.screen" flow="true">
        <action-class>org.seda.payer.manager.login.actions.CambioPswdAction</action-class>
		<flow  class="org.seda.payer.manager.login.actions.CambioPswdFlowAction" >
			<result value="default" screen="default.screen" applid="default"/>
			<result value="cambioPswd" screen="cambiopswd.screen"/>
			<result value="login" screen="login.screen"/>
		</flow>
        <ruleset>
			<rule name="tx_username" regex="username_regex">
        		<missing severity="continue"/>
        		<malformed severity="continue"><rule-action class="com.seda.j2ee5.maf.defender.action.impl.Blank"/></malformed>
        	</rule>
			<rule name="puk" regex="puk_regex">
        		<missing severity="continue"/>
        		<malformed severity="continue"><rule-action class="com.seda.j2ee5.maf.defender.action.impl.Blank"/></malformed>
        	</rule>
			<rule name="tx_password" regex="vecchia_password_regex">
        		<missing severity="continue"/>
        		<malformed severity="continue"><rule-action class="com.seda.j2ee5.maf.defender.action.impl.Blank"/></malformed>
        	</rule>
			<rule name="tx_nuova_password" regex="password_regex">
        		<missing severity="continue"/>
        		<malformed severity="continue"><rule-action class="com.seda.j2ee5.maf.defender.action.impl.Blank"/></malformed>
        	</rule>
			<rule name="tx_conferma_nuova_password" regex="password_regex">
        		<missing severity="continue"/>
        		<malformed severity="continue"><rule-action class="com.seda.j2ee5.maf.defender.action.impl.Blank"/></malformed>
        	</rule>
			<rule name="emailNotifiche" regex="email_regex">
        		<missing severity="continue"/>
        		<malformed severity="continue"><rule-action class="com.seda.j2ee5.maf.defender.action.impl.Blank"/></malformed>
        	</rule>
		</ruleset>
    </action>
    
    <action url="sceltaAut.do" flow="true">
        <action-class>org.seda.payer.manager.login.actions.SceltaAutenticazioneAction</action-class>
		<flow  class="org.seda.payer.manager.login.actions.SceltaAutenticazioneFlowAction" >
			<result value="proprietaria" screen="loginPdp.do"/>
			<result value="federata" redirect="urlRedirectDefault"/>
		</flow>
    </action>
    
    <action url="loginerror.do" screen="loginerror.screen">
        <action-class>org.seda.payer.manager.login.actions.LoginErrorAction</action-class>
    </action>

  
</actions-mapping>

=== regione-marche/org.seda.payer.manager.web/WebContent/applications/payer/ecmanager/maf-actions.xml
<?xml version="1.0" encoding="UTF-8"?>

<actions-mapping xmlns="http://action.core.maf.j2ee5.seda.com"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://action.core.maf.j2ee5.seda.com ../../../WEB-INF/xsd/maf-actions.xsd">
	
			
	<global-ruleset>
 		<regexset> 			
 			<regex name="codicefisc_regex">
 				<pattern>^[a-zA-Z]{6}[\d]{2}[a-zA-Z][\d]{2}[a-zA-Z][\d]{3}[a-zA-Z]|[0-9]{11}$</pattern>
 				<description></description>
 			</regex> 			
 		</regexset>
 	</global-ruleset>
			
	<!--<action url="default.do" screen="default.screen">
       <role-collection>
			<role>AMMI</role>
			<role>AMSO</role>
			<role>AMUT</role>
			<role>AMEN</role>
		</role-collection>
		<action-class>org.seda.payer.manager.ecmanager.actions.DefaultAction</action-class>
    </action>-->
    
    <action url="default.do" screen="logincontribuente.screen">
       <role-collection>
			<role>AMMI</role>
			<role>AMSO</role>
			<role>AMUT</role>
			<role>AMEN</role>
		</role-collection>
		<action-class>org.seda.payer.manager.ecmanager.actions.LoginContribuente</action-class>
    </action>
    
    <action url="logincontribuente.do" screen="logincontribuente.screen" flow="true">
		<role-collection>
			<role>AMMI</role>
			<role>AMSO</role>
			<role>AMUT</role>
			<role>AMEN</role>
		</role-collection>
        <action-class>org.seda.payer.manager.ecmanager.actions.LoginContribuente</action-class>
        <flow class="org.seda.payer.manager.flows.DispatchFlowEC">
			<result value="init" screen="logincontribuente.screen"/>
			<result value="avantiEC" redirect="urlRedirectEC"/>
		</flow>
		<ruleset>
        	<rule name="codicefiscale" regex="codicefisc_regex">
        		<missing severity="continue"/>
        		<malformed severity="fatal"/>
        	</rule>
        </ruleset> 			
    </action>
    
    <action url="ecanagrafica.do" screen="ecanagrafica.screen" flow="true">
		<role-collection>
			<role>AMMI</role>
			<role>AMSO</role>
			<role>AMUT</role>
			<role>AMEN</role>
		</role-collection>
        <action-class>org.seda.payer.manager.ecmanager.actions.AnagraficaBollettinoListaAction</action-class>
        <flow class="org.seda.payer.manager.flows.DispatchFlowEC">
			<result value="init" screen="ecanagrafica.screen"/>
			<result value="avantiEC" redirect="urlRedirectEC"/>
			<result value="DownloadCsv" writer="anagraficabollettinoAnag_csv" content-type="plain/txt" inScope="true" attach="nome_file_csv"/>
			<result value="download" writer="welcomekit_pdf" content-type="application/pdf" inScope="false" attach="filename"/>
		</flow>
		<ruleset>
        	<rule name="codicefiscale" regex="codicefisc_regex">
        		<missing severity="continue"/>
        		<malformed severity="fatal"/>
        	</rule>
        </ruleset> 			
    </action>
    
    <action url="ecanagraficaedit.do" screen="ecanagraficaedit.screen" flow="true">
		<role-collection>
			<role>AMMI</role>
			<role>AMSO</role>
			<role>AMUT</role>
			<role>AMEN</role>
		</role-collection>
        <action-class>org.seda.payer.manager.ecmanager.actions.AnagraficaBollettinoEditAction</action-class>
		<flow class="org.seda.payer.manager.walletmanager.flows.WalletAnagraficaContribuentiEditFlowAction">
           	<result value="Search" screen="ecanagraficaedit.screen" />
           	<result value="edit" screen="ecanagraficaedit.do" />
           	<result value="ritorna" screen="ecanagrafica.do" />           	
        </flow>
		<ruleset>
        	<rule name="codicefiscale" regex="codicefisc_regex">
        		<missing severity="continue"/>
        		<malformed severity="fatal"/>
        	</rule>
        </ruleset> 			
    </action>
    
     <action url="ecuffmanager.do" screen="ecuffmanager.screen" flow="true">
		<role-collection>
			<role>AMMI</role>
			<role>AMSO</role>
			<role>AMUT</role>
			<role>AMEN</role>
		</role-collection>
        <action-class>org.seda.payer.manager.ecmanager.actions.LoginUffManager</action-class>
        <flow class="org.seda.payer.manager.flows.DispatchFlowEC">
			<result value="init" screen="ecuffmanager.screen"/>
			<result value="avantiEC" redirect="urlRedirectEC"/>
		</flow>
		<ruleset>
        	<rule name="codicefiscale" regex="codicefisc_regex">
        		<missing severity="continue"/>
        		<malformed severity="fatal"/>
        	</rule>
        </ruleset> 	 			
    </action>
    
    <action url="ecnotifiche.do" screen="ecnotifiche.screen" flow="true">
		<role-collection>
			<role>AMMI</role>
			<role>AMSO</role>
			<role>AMUT</role>
			<role>AMEN</role>
		</role-collection>
        <action-class>org.seda.payer.manager.ecmanager.actions.EcNotificheListaAction</action-class>
        <flow class="org.seda.payer.manager.flows.DispatchFlowEC">
			<result value="init" screen="ecnotifiche.screen"/>
			<result value="avantiEC" redirect="urlRedirectEC"/>
			<result value="download" writer="filePath" content-type="application/pdf" inScope="false" attach="filename"/>
		</flow>
		<ruleset>
        	<rule name="codicefiscale" regex="codicefisc_regex">
        		<missing severity="continue"/>
        		<malformed severity="fatal"/>
        	</rule>
        </ruleset> 			
    </action>
    
    <action url="ecnotificheedit.do" screen="ecnotificheedit.screen" flow="true">
		<role-collection>
			<role>AMMI</role>
			<role>AMSO</role>
			<role>AMUT</role>
			<role>AMEN</role>
		</role-collection>
        <action-class>org.seda.payer.manager.ecmanager.actions.EcNotificheEditAction</action-class>
		<flow class="org.seda.payer.manager.walletmanager.flows.WalletAnagraficaContribuentiEditFlowAction">
           	<result value="Search" screen="ecnotificheedit.screen" />
           	<result value="edit" screen="ecnotificheedit.do" />
           	<result value="ritorna" screen="ecnotifiche.do" />           	
        </flow>
		<ruleset>
        	<rule name="codicefiscale" regex="codicefisc_regex">
        		<missing severity="continue"/>
        		<malformed severity="fatal"/>
        	</rule>
        </ruleset> 			
    </action>
    
</actions-mapping>

=== regione-marche/org.seda.payer.manager.web/WebContent/applications/payer/posfisico/maf-actions.xml
<?xml version="1.0" encoding="UTF-8"?>

<actions-mapping xmlns="http://action.core.maf.j2ee5.seda.com"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://action.core.maf.j2ee5.seda.com ../../../WEB-INF/xsd/maf-actions.xsd">
	
	<global-ruleset>
		<regexset>
			<regex name="codicefisc_piva_regex">
				<pattern>^[a-zA-Z]{6}[\d]{2}[a-zA-Z][\d]{2}[a-zA-Z][\d]{3}[a-zA-Z]|^[0-9]{11}$</pattern>
				<description></description>
			</regex>
		</regexset>
	</global-ruleset>
    <action url="posfisico.do" screen="posfisico.screen" flow="true">
		<role-collection>
			<role>OPER</role>
		</role-collection>
        <action-class>org.seda.payer.manager.posfisico.actions.PosFisico</action-class>
        <flow class="org.seda.payer.manager.flows.DispatchFlowEC">
			<result value="init" screen="posfisico.screen"/>
			<result value="avantiPOS" redirect="urlRedirectPOS"/>
		</flow>
		<ruleset>
			<rule name="tbEleCausaleServizio" regex="descrizione40_regex">
	       		<missing severity="continue"/>
	       		<malformed severity="continue">
					<rule-action class="com.seda.j2ee5.maf.defender.action.impl.Blank" />
				</malformed>
	       	</rule>	
       	</ruleset>
    </action>
    
    
</actions-mapping>

=== regione-marche/org.seda.payer.manager.web/WebContent/applications/payer/mercatimanager/maf-actions.xml
<?xml version="1.0" encoding="UTF-8"?>

<actions-mapping xmlns="http://action.core.maf.j2ee5.seda.com"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://action.core.maf.j2ee5.seda.com ../../../WEB-INF/xsd/maf-actions.xsd">
	
		<global-ruleset>
 		<regexset>
 			<regex name="descrizione_regex">
 				<pattern>^[a-zA-Z]+(([\'\,\.\- ][a-zA-Z ])?[a-zA-Z]*)*{1,256}$</pattern>
 				<description></description>
 			</regex> 
 			<regex name="codice3char_regex">
 				<pattern>^\w{1,3}$</pattern>
 				<description></description>
 			</regex>
 			<regex name="date_yyyy_mm_dd_regex">
 				<pattern>^(19|20)\d\d([-])(0[1-9]|1[012])([-])(0[1-9]|[12][0-9]|3[01])$</pattern>
 				<description></description>
 			</regex>
 			<regex name="codice20char_regex">
 				<pattern>^\w{1,20}$</pattern>
 				<description></description>
 			</regex>
 			<regex name="codicefisc_regex">
 				<pattern>^[a-zA-Z]+(([\'\,\.\- ][a-zA-Z ])?[a-zA-Z]*)*{1,16}$</pattern>
 				<description></description>
 			</regex>
 			
 		</regexset>
 	</global-ruleset>
			
    	<!-- MERCATI MONITORAGGIO -->
    <action url="monitoraggiomercati" screen="monitoraggioMercati.screen" flow="true">
		<role-collection>
			<role>AMMI</role>
			<role>AMSO</role>
			<role>AMUT</role>
			<role>AMEN</role>
		</role-collection>
        <action-class>org.seda.payer.manager.mercatimonitoraggio.actions.MonitoraggioMercatiAction</action-class>
        <flow class="org.seda.payer.manager.mercatimonitoraggio.actions.MonitoraggioMercatiFlow">
           	<result value="Search" screen="monitoraggioMercati.screen" />
        	<result value="download" writer="fileCsv" content-type="plain/txt" inScope="true" attach="filename"/>
			 
        </flow>
         <ruleset>
        	<rule name="pageNumber" regex="num8_regex">
        		<missing severity="continue"/>
        		<malformed severity="continue"><rule-action class="com.seda.j2ee5.maf.defender.action.impl.Blank"/></malformed>
        	</rule>
        	<rule name="rowsPerPage" regex="num3_regex">
        		<missing severity="continue"/>
        		<malformed severity="continue"><rule-action class="com.seda.j2ee5.maf.defender.action.impl.Blank"/></malformed>
        	</rule>
        	
        	<rule name="tx_societa" regex="codice5obblchar_regex">
        		<missing severity="continue"/>
        		<malformed severity="continue"><rule-action class="com.seda.j2ee5.maf.defender.action.impl.Blank"/></malformed>
        	</rule>
			<rule name="tx_utente" regex="codice5obblchar_regex">
        		<missing severity="continue"/>
        		<malformed severity="continue"><rule-action class="com.seda.j2ee5.maf.defender.action.impl.Blank"/></malformed>
        	</rule>
			<rule name="tx_provincia" regex="codice2obblchar_regex"> 
        		<missing severity="continue"/>
        		<malformed severity="continue"><rule-action class="com.seda.j2ee5.maf.defender.action.impl.Blank"/></malformed>
        	</rule>
			<rule name="tx_ente" regex="codice10obblchar_regex">
        		<missing severity="continue"/>
        		<malformed severity="continue"><rule-action class="com.seda.j2ee5.maf.defender.action.impl.Blank"/></malformed>
        	</rule>
			
        </ruleset> 			
    </action>
    
       	<!-- MERCATI MONITORAGGIO -->
   
    
   
   
    <action url="mercatimanager.do" screen="mercatimanager.screen" flow="true">
		<role-collection>
			<role>AMMI</role>
			<role>AMSO</role>
			<role>AMUT</role>
			<role>AMEN</role>
		</role-collection>
        <action-class>org.seda.payer.manager.mercatomanager.actions.MercatiManager</action-class>
        <flow class="org.seda.payer.manager.flows.DispatchFlowEC">
			<result value="init" screen="mercatimanager.screen"/>
			<result value="avantiMercati" redirect="urlRedirectWallet"/>
		</flow>
	</action>

	<action url="backmanager.do" screen="mercatimanager.screen" flow="true">
		<role-collection>
			<role>AMMI</role>
			<role>AMSO</role>
			<role>AMUT</role>
			<role>AMEN</role>
		</role-collection>
        <action-class>org.seda.payer.manager.mercatomanager.actions.MercatiManager</action-class>
        <flow class="org.seda.payer.manager.flows.DispatchFlowEC">
			<result value="init" screen="mercatimanager.screen"/>
		</flow>
	</action>
    
    
	<action url="ritorna.do" flow="true">
		<role-collection>
			<role>AMMI</role>
			<role>AMSO</role>
			<role>AMUT</role>
			<role>AMEN</role>
	    </role-collection>
		<description>Action per la gestione del ritorno ad altro screen con viewstate</description>
        <action-class>org.seda.payer.manager.mercatimonitoraggio.actions.RitornaAction</action-class>
        <flow class="org.seda.payer.manager.mercatimonitoraggio.actions.RitornaFlowAction">
           	<result value="monitoraggiomercati" screen="monitoraggiomercati.do" />           	
        </flow>
    </action> 
    
    
</actions-mapping>

=== regione-marche/org.seda.payer.manager.web/WebContent/applications/payer/gestioneuffici/maf-actions.xml
<?xml version="1.0" encoding="UTF-8"?>

<actions-mapping xmlns="http://action.core.maf.j2ee5.seda.com"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://action.core.maf.j2ee5.seda.com ../../../WEB-INF/xsd/maf-actions.xsd">
	
	<global-ruleset>
 		<regexset>
 			<regex name="descrizione_regex">
 				<pattern>^[a-zA-Z]+(([\'\,\.\- ][a-zA-Z ])?[a-zA-Z]*)*{1,256}$</pattern>
 				<description></description>
 			</regex>
 		</regexset>
 	</global-ruleset>
			
    <action url="gestioneuffici.do" screen="gestioneuffici.screen" flow="true">
		<role-collection>
			<role>AMMI</role>
			<role>AMSO</role>
			<role>AMUT</role>
			<role>AMEN</role>
		</role-collection>
        <action-class>org.seda.payer.manager.configurazione.actions.GestioneUfficiAction</action-class>
        <flow class="org.seda.payer.manager.configurazione.flows.GestioneUfficiFlowAction">
           	<result value="Search" screen="gestioneuffici.screen" />
           	<result value="Add" screen="gestioneufficiadd.screen" />
           	<result value="Edit" screen="gestioneufficiedit.screen" />
           	<result value="Cancel" screen="gestioneufficicancel.screen" />
        </flow>	
    </action>
    
</actions-mapping>
