=== regione-marche/org.seda.payer.manager.web/WebContent/WEB-INF/xsd/maf-applications.xsd
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
targetNamespace="http://application.core.maf.j2ee5.seda.com"
xmlns="http://application.core.maf.j2ee5.seda.com"
elementFormDefault="qualified">

<xsd:element name="applications-mapping" type="applicationsMappingType"/>

<xsd:complexType name="applicationsMappingType">
	<xsd:sequence>
		<xsd:element name="default" type="defaultType"  minOccurs="1" maxOccurs="1"/>
		<xsd:element name="security" type="securityType"  minOccurs="0" maxOccurs="1"/>
		<xsd:element name="menu-collection" type="menuCollectionType"  minOccurs="0" maxOccurs="1"/>		
		<xsd:element name="application" type="applicationType"  minOccurs="0" maxOccurs="unbounded"/>
    </xsd:sequence>
</xsd:complexType>

<xsd:complexType name="defaultType">
	<xsd:sequence>
		<xsd:element name="config-path" type="xsd:string" minOccurs="1" maxOccurs="1"/>
		<xsd:element name="applid" type="xsd:string" minOccurs="1" maxOccurs="1"/>		
		<xsd:element name="ignored-ext" type="xsd:string" minOccurs="0" maxOccurs="1"/>		
		<xsd:element name="ignored-subcontext" type="xsd:string" minOccurs="0" maxOccurs="1"/>		
    </xsd:sequence>
</xsd:complexType>

<xsd:complexType name="securityType">
	<xsd:sequence>
		<xsd:element name="login-page" type="xsd:string" minOccurs="1" maxOccurs="1"/>
		<xsd:element name="security-error-page" type="xsd:string" minOccurs="0" maxOccurs="1"/>			
		<xsd:element name="signon-class" type="xsd:string" minOccurs="0" maxOccurs="1"/>
		<xsd:element name="sso-class" type="xsd:string" minOccurs="0" maxOccurs="1"/>		
		<xsd:element name="after-login" type="xsd:string" minOccurs="1" maxOccurs="1"/>
		<xsd:element name="locked-timeout" type="xsd:int" minOccurs="0" maxOccurs="1"/>
		<xsd:element name="login-ruleset" type="loginRuleSetType" minOccurs="1" maxOccurs="1"/>		
    </xsd:sequence>
    <xsd:attribute name="enabled" type="xsd:boolean" use="optional"/>    
</xsd:complexType>

<xsd:complexType name="loginRuleSetType">
	<xsd:sequence>
		<xsd:element name="username-regex" type="xsd:string" minOccurs="0" maxOccurs="1"/>
		<xsd:element name="password-regex" type="xsd:string" minOccurs="0" maxOccurs="1"/>
		<xsd:element name="attempts" type="xsd:int" minOccurs="0" maxOccurs="1"/>
		<xsd:element name="locked-timeout" type="xsd:int" minOccurs="0" maxOccurs="1"/>
		<xsd:element name="msg-invalid" type="xsd:string" minOccurs="0" maxOccurs="1"/>		
		<xsd:element name="msg-locked" type="xsd:string" minOccurs="0" maxOccurs="1"/>
		<xsd:element name="msg-notfound" type="xsd:string" minOccurs="0" maxOccurs="1"/>
		<xsd:element name="msg-notsignedon" type="xsd:string" minOccurs="0" maxOccurs="1"/>		
		<xsd:element name="msg-lowprofile" type="xsd:string" minOccurs="0" maxOccurs="1"/>		
		<xsd:element name="msg-lowrole" type="xsd:string" minOccurs="0" maxOccurs="1"/>		
    </xsd:sequence>    
</xsd:complexType>

<xsd:complexType name="menuCollectionType">
	<xsd:sequence>
		<xsd:element name="menu" type="menuType" minOccurs="1" maxOccurs="unbounded"/>	
    </xsd:sequence>    	
</xsd:complexType>
		
<xsd:complexType name="menuType">
	<xsd:sequence>
		<xsd:element name="link" type="menuLinkType" minOccurs="1" maxOccurs="unbounded"/>	
    </xsd:sequence>
    <xsd:attribute name="template" type="xsd:string" use="required"/>
</xsd:complexType>

<xsd:complexType name="menuLinkType">
	<xsd:attribute name="text" type="xsd:string" use="required"/>    
	<xsd:attribute name="applid" type="xsd:string" use="required"/>
	<xsd:attribute name="enabled" type="xsd:boolean" use="optional"/>
</xsd:complexType>

<xsd:complexType name="applicationType">
	<xsd:sequence>
		<xsd:element name="profile-collection" type="applicationProfileType" minOccurs="0" maxOccurs="1"/>	
	
		<xsd:element name="description" type="xsd:string" minOccurs="0" maxOccurs="1"/>
		<xsd:element name="remember-protected-url" type="xsd:string" minOccurs="0" maxOccurs="1"/>
				
		<xsd:element name="config-path" type="xsd:string" minOccurs="1" maxOccurs="1"/>
		
		<xsd:element name="template-collection" type="templateCollectionType" minOccurs="0" maxOccurs="1"/>
		
		<xsd:element name="subcontext" type="xsd:string" minOccurs="1" maxOccurs="1"/>
		<xsd:element name="welcome" type="xsd:string" minOccurs="1" maxOccurs="1"/>		

		<xsd:element name="starter-class" type="xsd:string" minOccurs="0" maxOccurs="1"/>
				
		<xsd:element name="controller-servlet" type="xsd:string" minOccurs="0" maxOccurs="1"/>
		
		<xsd:element name="binder-class" type="xsd:string" minOccurs="0" maxOccurs="1"/>		
		
		<xsd:element name="session-class" type="xsd:string" minOccurs="0" maxOccurs="1"/>
		<xsd:element name="captcha" type="captchaType" minOccurs="0" maxOccurs="1"/>		
    </xsd:sequence>
    <xsd:attribute name="name" type="xsd:string" use="required"/>
    <xsd:attribute name="activate" type="xsd:boolean" use="optional"/>
	<xsd:attribute name="protected" type="xsd:boolean" use="optional"/>        
</xsd:complexType>

<xsd:complexType name="templateCollectionType">
	<xsd:sequence>
		<xsd:element name="template" type="templateType" minOccurs="1" maxOccurs="unbounded"/>	
    </xsd:sequence>    	
</xsd:complexType>

<xsd:complexType name="templateType" >
	<xsd:simpleContent>
		<xsd:extension base="xsd:string">
			<xsd:attribute name="name" type="xsd:string" use="required"/>
		</xsd:extension>
	</xsd:simpleContent>
</xsd:complexType>

<xsd:complexType name="applicationProfileType">
	<xsd:sequence>
		<xsd:element name="profile" type="xsd:string" minOccurs="1" maxOccurs="unbounded"/>	
    </xsd:sequence>    	
</xsd:complexType>

<xsd:complexType name="captchaType">
	<xsd:sequence>
		<xsd:element name="captcha-url" type="xsd:string" minOccurs="1" maxOccurs="1"/>	
		<xsd:element name="captcha-class" type="xsd:string" minOccurs="0" maxOccurs="1"/>		
    </xsd:sequence>    	
</xsd:complexType>

</xsd:schema>

=== regione-marche/org.seda.payer.manager.web/WebContent/WEB-INF/maf-applications.xml
<?xml version="1.0" encoding="UTF-8"?>
<applications-mapping xmlns="http://application.core.maf.j2ee5.seda.com"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://application.core.maf.j2ee5.seda.com xsd/maf-applications.xsd">
	<default>
		<config-path>/WebContent/applications</config-path>
		<applid>login</applid>
		<ignored-ext>.css .js .jpg .gif .pdf .png .PNG .jks .xml .jsp .properties</ignored-ext>
		<ignored-subcontext>/MetadataPublisherServlet /metadata /AssertionConsumerService /metadataAR /metadataGW /DisplayChart /GetChart /Print /xmla /SingleLogoutService /ext/bolzanoExt</ignored-subcontext>
	</default>
	<security enabled="true">
		<login-page>/login/login.do</login-page>
		<security-error-page>/login/loginerror.do</security-error-page>
		<signon-class>org.seda.payer.manager.login.actions.SignOnSupport</signon-class>
		<sso-class>org.seda.payer.manager.login.actions.SSOSupport</sso-class>
		<after-login>/default/default.do</after-login>
		<locked-timeout>1</locked-timeout> 
		<login-ruleset>
			<username-regex>^[a-zA-Z0-9].{3,50}$</username-regex>
			<password-regex>^[a-zA-Z0-9\.,!#%]{3,15}$</password-regex>
			<attempts>3</attempts> 
			<locked-timeout>1</locked-timeout>
			<msg-invalid>Lo username o la password non sono sintatticamente corrette.</msg-invalid>
			<msg-locked>Il tuo account risulta bloccato. Contatta l'amministratore di sistema.</msg-locked>
			<msg-notfound>Il tuo account non risulta censito.</msg-notfound>
			<msg-notsignedon>Si prega di eseguire il login.</msg-notsignedon>
			<msg-lowprofile>Non ha i requisiti di autorizzazione sufficienti per la sua richiesta.</msg-lowprofile>
			<msg-lowrole>Non ha i requisiti di autorizzazione sufficienti per la sua richiesta.</msg-lowrole>			
		</login-ruleset> 
	</security>
 	
 	<application name="login" protected="false" activate="true">
		<description>Applicazione di Login</description>	
		<config-path>/applications/payer/login</config-path>
		<template-collection>
			<template name="default">maf-templates.xml</template>
			<template name="lepida">maf-templates-lepida.xml</template>
			<template name="soris">maf-templates-soris.xml</template>
			<template name="trentrisc">maf-templates-trentrisc.xml</template>
			<template name="bolzano">maf-templates-bolzano.xml</template>
			<template name="aosta">maf-templates-aosta.xml</template>
			<template name="maggioli">maf-templates-maggioli.xml</template>
			<template name="sassari">maf-templates-sassari.xml</template>
			<template name="consbonrm">maf-templates-consbonrm.xml</template>
			<template name="sap">maf-templates-sap.xml</template>
			<template name="padanatech">maf-templates-padanatech.xml</template>
			<template name="fccsa">maf-templates-fccsa.xml</template>
			<template name="cbec">maf-templates-cbec.xml</template>
			<template name="provroma">maf-templates-provroma.xml</template>
			<template name="serc">maf-templates-serc.xml</template>
			<template name="regabruzzo">maf-templates-regabruzzo.xml</template>
			<template name="roseto">maf-templates-roseto.xml</template>
			<template name="creset">maf-templates-creset.xml</template>
            <template name="regmarche">maf-templates-regmarche.xml</template>
            <!--PG200400-->
			<template name="newsoris">maf-templates-soris.xml</template>
			<!--FINE PG200400-->  
		</template-collection>
		<subcontext>/login</subcontext>
		<welcome>login.do</welcome>
	</application>
 	
 	<application name="default" protected="true" activate="true">
 		<profile-collection>
			<profile>AMMI</profile>
			<profile>AMSO</profile>
			<profile>AMUT</profile>
			<profile>AMEN</profile>
			<profile>PROF</profile>
			<profile>OPER</profile>
		</profile-collection>
		<description>Applicazione di default per la gestione del men√π</description>	
		<config-path>/applications/payer/default</config-path>
		<template-collection>
			<template name="default">maf-templates.xml</template>
			<template name="lepida">maf-templates-lepida.xml</template>
			<template name="soris">maf-templates-soris.xml</template>
			<template name="trentrisc">maf-templates-trentrisc.xml</template>
			<template name="bolzano">maf-templates-bolzano.xml</template>
			<template name="aosta">maf-templates-aosta.xml</template>
			<template name="maggioli">maf-templates-maggioli.xml</template>
			<template name="sassari">maf-templates-sassari.xml</template>
			<template name="consbonrm">maf-templates-consbonrm.xml</template>
			<template name="sap">maf-templates-sap.xml</template>
			<template name="padanatech">maf-templates-padanatech.xml</template>
			<template name="fccsa">maf-templates-fccsa.xml</template>
			<template name="regabruzzo">maf-templates-regabruzzo.xml</template>
			<template name="roseto">maf-templates-roseto.xml</template>
			<template name="cbec">maf-templates-cbec.xml</template>
			<template name="provroma">maf-templates-provroma.xml</template>
			<template name="serc">maf-templates-serc.xml</template>
			<template name="creset">maf-templates-creset.xml</template>
            <template name="regmarche">maf-templates-regmarche.xml</template>
            <!--PG200400-->
			<template name="newsoris">maf-templates-soris.xml</template>
			<!--FINE PG200400-->  
		</template-collection>
		<subcontext>/default</subcontext>
		<welcome>default.do</welcome>
		<starter-class>org.seda.payer.manager.components.config.ManagerStarter</starter-class>
		<binder-class>org.seda.payer.manager.components.config.Binder</binder-class>
		<session-class>org.seda.payer.manager.components.listeners.SessionHandler</session-class>
	</application>

	<application name="entrate" protected="true" activate="true">
		<profile-collection>
		<profile>AMMI</profile>
		<profile>AMSO</profile>
		<profile>AMUT</profile>
		<profile>AMEN</profile>
		</profile-collection>
		<description>Entrate</description>
		<config-path>/applications/payer/entrate</config-path>
		<template-collection>
			<template name="default">maf-templates.xml</template>
			<template name="lepida">maf-templates-lepida.xml</template>
			<template name="aosta">maf-templates-aosta.xml</template>
			<template name="maggioli">maf-templates-maggioli.xml</template>
			<template name="sassari">maf-templates-sassari.xml</template>
			<template name="consbonrm">maf-templates-consbonrm.xml</template>
			<template name="sap">maf-templates-sap.xml</template>
			<template name="fccsa">maf-templates-fccsa.xml</template>
			<template name="regabruzzo">maf-templates-regabruzzo.xml</template>
			<template name="roseto">maf-templates-roseto.xml</template>
			<template name="padanatech">maf-templates-padanatech.xml</template>
			<template name="creset">maf-templates-creset.xml</template>
            <template name="regmarche">maf-templates-regmarche.xml</template>  
		</template-collection>
		<subcontext>/entrate</subcontext>
		<welcome>ricercaAnagrafiche.do</welcome>
		<binder-class>org.seda.payer.manager.components.config.Binder</binder-class>
	</application>

	<application name="ruoli" protected="true" activate="true">
		<profile-collection>
		<profile>AMMI</profile>
		<profile>AMSO</profile>
		<profile>AMUT</profile>
		<profile>AMEN</profile>
		</profile-collection>
		<description>Ruoli</description>
		<config-path>/applications/payer/ruoli</config-path>
		<template-collection>
			<template name="default">maf-templates.xml</template>
			<template name="lepida">maf-templates-lepida.xml</template>
			<template name="consbonrm">maf-templates-consbonrm.xml</template>
			<template name="sap">maf-templates-sap.xml</template>
			<template name="padanatech">maf-templates-padanatech.xml</template>
			<template name="fccsa">maf-templates-fccsa.xml</template>
			<template name="regabruzzo">maf-templates-regabruzzo.xml</template>
			<template name="roseto">maf-templates-roseto.xml</template>
			<template name="creset">maf-templates-creset.xml</template>
            <template name="regmarche">maf-templates-regmarche.xml</template>  
		</template-collection>
		<subcontext>/ruoli</subcontext>
		<welcome>ricercaAnagrafiche.do</welcome>
		<binder-class>org.seda.payer.manager.components.config.Binder</binder-class>
	</application>


	<application name="monitoraggio" protected="true" activate="true">
		<profile-collection>
			<profile>AMMI</profile>
			<profile>AMSO</profile>
			<profile>AMUT</profile>
			<profile>AMEN</profile>
		</profile-collection>
		<description>Monitoraggio transazioni</description>
		<config-path>/applications/payer/monitoraggio</config-path>
		<template-collection>
			<template name="default">maf-templates.xml</template>
			<template name="lepida">maf-templates-lepida.xml</template>
			<template name="trentrisc">maf-templates-trentrisc.xml</template>
			<template name="bolzano">maf-templates-bolzano.xml</template>
			<template name="aosta">maf-templates-aosta.xml</template>
			<template name="maggioli">maf-templates-maggioli.xml</template>
			<template name="sassari">maf-templates-sassari.xml</template>
			<template name="consbonrm">maf-templates-consbonrm.xml</template>
			<template name="sap">maf-templates-sap.xml</template>
			<template name="padanatech">maf-templates-padanatech.xml</template>
			<template name="fccsa">maf-templates-fccsa.xml</template>
			<template name="regabruzzo">maf-templates-regabruzzo.xml</template>
			<template name="roseto">maf-templates-roseto.xml</template>
			<template name="cbec">maf-templates-cbec.xml</template>
			<template name="provroma">maf-templates-provroma.xml</template>
			<template name="serc">maf-templates-serc.xml</template>
			<template name="soris">maf-templates-soris.xml</template>
			<template name="creset">maf-templates-creset.xml</template>
            <template name="regmarche">maf-templates-regmarche.xml</template>  
            <!--PG200400-->
			<template name="newsoris">maf-templates-soris.xml</template>
			<!--FINE PG200400-->
		</template-collection>
		<subcontext>/monitoraggio</subcontext>
		<welcome>monitoraggioTransazioni.do</welcome>
