=== regione-marche/org.seda.payer.manager.web/WebContent/WEB-INF/xsd/maf-actions.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
targetNamespace="http://action.core.maf.j2ee5.seda.com"
xmlns="http://action.core.maf.j2ee5.seda.com"
elementFormDefault="qualified">
 
<xsd:annotation>
 	<xsd:documentation xml:lang="en">
    </xsd:documentation>
</xsd:annotation>

<xsd:element name="actions-mapping" type="actionsMappingType"/>
  
<xsd:complexType name="actionsMappingType">
	<xsd:sequence>
		<xsd:element name="menu" type="menuType" minOccurs="0" maxOccurs="1"/>
		<xsd:element name="complex-actions" type="complexType" minOccurs="0" maxOccurs="1"/>
		<xsd:element name="global-ruleset" type="globalRulesetType" minOccurs="0" maxOccurs="1"/>
		<xsd:element name="action" type="actionType" minOccurs="0" maxOccurs="unbounded"/>
    </xsd:sequence>
</xsd:complexType>

<xsd:complexType name="menuType">
	<xsd:sequence>
		<xsd:element name="link" type="menuLinkType" minOccurs="1" maxOccurs="unbounded"/>	
    </xsd:sequence>    
</xsd:complexType>

<xsd:complexType name="menuLinkType">
	<xsd:attribute name="text" type="xsd:string" use="required"/>	
	<xsd:attribute name="actionurl" type="xsd:string" use="required"/>
	<xsd:attribute name="enabled" type="xsd:boolean" use="optional"/>
</xsd:complexType>

<xsd:complexType name="complexType">
	<xsd:sequence>
		<xsd:element name="complex-target" type="complexTargetType" minOccurs="1" maxOccurs="unbounded"/>	
    </xsd:sequence>    
</xsd:complexType>

<xsd:complexType name="complexTargetType">
	<xsd:attribute name="value" type="xsd:string" use="required"/>	
	<xsd:attribute name="actionurl" type="xsd:string" use="required"/>
</xsd:complexType>

<xsd:complexType name="globalRulesetType">
	<xsd:sequence>
		<xsd:element name="regexset" type="regexsetType" minOccurs="0" maxOccurs="unbounded"/>	
		<xsd:element name="ruleset" type="rulesetType" minOccurs="0" maxOccurs="unbounded"/>
    </xsd:sequence>
</xsd:complexType>

<xsd:complexType name="regexsetType">
	<xsd:sequence>
		<xsd:element name="regex" type="regexType" minOccurs="1" maxOccurs="unbounded"/>
	</xsd:sequence>
</xsd:complexType>

<xsd:complexType name="regexType">
	<xsd:sequence>
		<xsd:element name="pattern" type="xsd:string" minOccurs="1" maxOccurs="1"/>
		<xsd:element name="description" type="xsd:string" minOccurs="1" maxOccurs="1"/>
	</xsd:sequence>
	<xsd:attribute name="name" type="xsd:string" use="required"/>	
</xsd:complexType>

<xsd:complexType name="rulesetType">
	<xsd:sequence>
		<xsd:element name="rule" type="ruleType" minOccurs="0" maxOccurs="unbounded"/>
	</xsd:sequence>
</xsd:complexType>

<xsd:complexType name="ruleType">
	<xsd:sequence>
		<xsd:element name="validation" type="xsd:string" minOccurs="0" maxOccurs="1"/>
		<xsd:element name="missing" type="ruleCategoryType" minOccurs="1" maxOccurs="1"/>
		<xsd:element name="malformed" type="ruleCategoryType" minOccurs="1" maxOccurs="1"/>
	</xsd:sequence>
	<xsd:attribute name="name" type="xsd:string" use="required"/>
	<xsd:attribute name="regex" type="xsd:string"/>
</xsd:complexType>

<xsd:complexType name="ruleCategoryType">
	<xsd:sequence>
		<xsd:element name="rule-action" type="ruleActionType" minOccurs="0" maxOccurs="unbounded"/>
	</xsd:sequence>
	<xsd:attribute name="severity" use="required">
		<xsd:simpleType>
			<xsd:restriction base="xsd:string">
				<!-- xsd:enumeration value="ignore"/ -->
				<xsd:enumeration value="continue"/>				
				<xsd:enumeration value="fatal"/>
			</xsd:restriction>
		</xsd:simpleType>
	</xsd:attribute>
</xsd:complexType>

<xsd:complexType name="ruleActionType">
	<xsd:sequence>
		<xsd:element name="parameter" type="ruleActionParameterType" minOccurs="0" maxOccurs="unbounded"/>
	</xsd:sequence>
	<xsd:attribute name="class" use="required"/>
</xsd:complexType>

<xsd:complexType name="ruleActionParameterType">
	<xsd:attribute  name="name" type="xsd:string" use="required"/>
	<xsd:attribute  name="value" type="xsd:string" use="required"/>
</xsd:complexType>

<xsd:complexType name="actionType">
	<xsd:sequence>
		<xsd:element name="role-collection" type="actionRoleType" minOccurs="0" maxOccurs="1"/>
		<xsd:element name="description" type="xsd:string" minOccurs="0" maxOccurs="1"/>			
		<xsd:element name="action-class" type="xsd:string"/>
		<xsd:element name="flow" type="flowType" minOccurs="0" maxOccurs="1"/>
		<xsd:element name="writer" type="writerType" minOccurs="0" maxOccurs="1"/>
		<xsd:element name="redirect" type="redirectType" minOccurs="0" maxOccurs="1"/>
		<xsd:element name="settings" type="settingsType" minOccurs="0" maxOccurs="1"/>				
		<xsd:element name="ruleset" type="rulesetType" minOccurs="0" maxOccurs="1"/>		
    </xsd:sequence>
    <xsd:attribute name="url" type="xsd:string" use="required"/>
    <xsd:attribute name="menuaction" type="xsd:string"/>    
    <xsd:attribute name="screen" type="xsd:string" />
    <xsd:attribute name="flow" type="xsd:boolean" />    
    <xsd:attribute name="writer" type="xsd:boolean" />    
    <xsd:attribute name="redirect" type="xsd:boolean" />    
    <xsd:attribute name="csrf" type="xsd:boolean" />    
</xsd:complexType>

<xsd:complexType name="actionRoleType">
	<xsd:sequence>
		<xsd:element name="role" type="xsd:string" minOccurs="1" maxOccurs="unbounded"/>	
    </xsd:sequence>    	
</xsd:complexType>

<xsd:complexType name="flowType">
	<xsd:sequence>
		<xsd:element name="settings" type="settingsType" minOccurs="0" maxOccurs="1"/>
		<xsd:element name="properties" type="propertiesType" minOccurs="0" maxOccurs="1"/>	
		<xsd:element name="result" type="resultType" minOccurs="1" maxOccurs="unbounded"/>
    </xsd:sequence>
    <xsd:attribute name="class" type="xsd:string" use="required"/>
</xsd:complexType>

<xsd:complexType name="resultType">
    <xsd:attribute name="value" type="xsd:string" use="required"/>
    <xsd:attribute name="screen" type="xsd:string"/>
    <xsd:attribute name="applid" type="xsd:string"/>
    <xsd:attribute name="writer" type="xsd:string"/>    
    <xsd:attribute name="redirect" type="xsd:string"/>
    <xsd:attribute name="inScope" type="xsd:boolean"/>
	<xsd:attribute name="content-type" type="xsd:string"/>    
	<xsd:attribute name="attach" type="xsd:string"/>
</xsd:complexType>

<xsd:complexType name="writerType">
    <xsd:attribute name="id" type="xsd:string" use="required"/>
	<xsd:attribute name="attach" type="xsd:string"/>    
	<xsd:attribute name="scope">
		<xsd:simpleType>
			<xsd:restriction base="xsd:string">
				<xsd:enumeration value="application"/>
				<xsd:enumeration value="session"/>				
				<xsd:enumeration value="request"/>
			</xsd:restriction>
		</xsd:simpleType>
	</xsd:attribute>
	<xsd:attribute name="inScope" type="xsd:boolean"/>
	<xsd:attribute name="content-type" type="xsd:string" use="required"/>
</xsd:complexType>

<xsd:complexType name="redirectType">
    <xsd:attribute name="id" type="xsd:string"/>
	<xsd:attribute name="url" type="xsd:string"/>    
</xsd:complexType>  

<xsd:complexType name="settingsType">
	<xsd:sequence>
		<xsd:element name="property" type="propertyType" minOccurs="1" maxOccurs="unbounded"/>
    </xsd:sequence>    
</xsd:complexType>

<xsd:complexType name="propertiesType">
	<xsd:sequence>
		<xsd:element name="property" type="propertyType" minOccurs="1" maxOccurs="unbounded"/>
    </xsd:sequence>    
</xsd:complexType>    

<xsd:complexType name="propertyType">
    <xsd:attribute name="key" type="xsd:string" use="required"/>
	<xsd:attribute name="value" type="xsd:string" use="required"/>    
</xsd:complexType>  
  
</xsd:schema>

=== regione-marche/org.seda.payer.manager.web/WebContent/applications/payer/riconciliazionemt/maf-actions.xml
<?xml version="1.0" encoding="UTF-8"?>

<actions-mapping xmlns="http://action.core.maf.j2ee5.seda.com"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://action.core.maf.j2ee5.seda.com ../../../WEB-INF/xsd/maf-actions.xsd">
	
	<action url="ricercaGiornaliCassa.do" screen="ricercaGiornaliCassa.screen" flow="true">
        <action-class>org.seda.payer.manager.riconciliazionemt.actions.RicercaGiornaliCassaAction</action-class>
        <flow class="org.seda.payer.manager.riconciliazionemt.flows.RicercaGiornaliCassaFlow">
        	<result value="ricerca" screen="ricercaGiornaliCassa.screen"/>
			<result value="stampa" writer="stampa" content-type="application/pdf" inScope="false" attach="filename"/>
        </flow>
    </action>
    
	<action url="caricaGiornaleCassa.do" screen="caricaGiornaleCassa.screen" flow="false">
        <action-class>org.seda.payer.manager.riconciliazionemt.actions.CaricaGiornaleCassaAction</action-class>
    </action>
    
    <action url="dettaglioGiornaleCassa.do" screen="dettaglioGiornaleCassa.screen" flow="false">
        <action-class>org.seda.payer.manager.riconciliazionemt.actions.DettaglioGiornaleCassaAction</action-class>
    </action>
    
    <action url="upload.do" screen="caricaGiornaleCassa.screen" flow="false" csrf="false">
        <action-class>org.seda.payer.manager.riconciliazionemt.actions.UploadAction</action-class>
    </action>
    
    <action url="dettaglioMovimentoCassa.do" screen="dettaglioMovimentoCassa.screen" flow="false">
        <action-class>org.seda.payer.manager.riconciliazionemt.actions.DettaglioMovimentoCassaAction</action-class>
    </action>
    
    <action url="dettaglioAssociazioniMovimentoCassa.do" screen="dettaglioAssociazioniMovimentoCassa.screen" flow="false">
        <action-class>org.seda.payer.manager.riconciliazionemt.actions.DettaglioAssociazioniMovimentoCassaAction</action-class>
    </action>
    
    <action url="associazioniFlussiMovimentoCassa.do" screen="associazioniFlussiMovimentoCassa.screen" flow="false">
        <action-class>org.seda.payer.manager.riconciliazionemt.actions.AssociazioniFlussiMovimentoCassaAction</action-class>
    </action>
    
    <action url="associazioniTransazioniMovimentoCassa.do" screen="associazioniTransazioniMovimentoCassa.screen" flow="false">
        <action-class>org.seda.payer.manager.riconciliazionemt.actions.AssociazioniTransazioniMovimentoCassaAction</action-class>
    </action>
    
    <action url="regolarizzaSospeso.do" screen="regolarizzaSospeso.screen" flow="false">
        <action-class>org.seda.payer.manager.riconciliazionemt.actions.RegolarizzaSospesoAction</action-class>
    </action>
	
    <action url="ritorna.do" flow="true">
		<description>Action per la gestione del ritorno ad altro screen con viewstate</description>
        <action-class>org.seda.payer.manager.riconciliazionemt.actions.RitornaAction</action-class>
        <flow class="org.seda.payer.manager.riconciliazionemt.flows.RitornaFlowManager">
           	<result value="ricercagiornalicassa" screen="ricercaGiornaliCassa.do" />
        </flow>
    </action> 
    
</actions-mapping>

=== regione-marche/org.seda.payer.manager.web/WebContent/applications/payer/analysis/maf-actions.xml
<?xml version="1.0" encoding="UTF-8"?>

<actions-mapping xmlns="http://action.core.maf.j2ee5.seda.com"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://action.core.maf.j2ee5.seda.com ../../../WEB-INF/xsd/maf-actions.xsd">
	 
	<global-ruleset>
 		<regexset>
 			<regex name="test">
 				<pattern>^[a-zA-Z0-9]{8,20}$</pattern>
 				<description></description>
 			</regex>
 		</regexset>
 	</global-ruleset>
 	
 	<action  url="analysis.do" screen="analysis.screen" csrf="false" >
       <action-class>org.seda.payer.manager.analysis.actions.AnalysisAction</action-class>
    </action>
     	
</actions-mapping>

=== regione-marche/org.seda.payer.manager.web/WebContent/applications/payer/riconciliazionenn/maf-actions.xml
<?xml version="1.0" encoding="UTF-8"?>

<actions-mapping xmlns="http://action.core.maf.j2ee5.seda.com"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://action.core.maf.j2ee5.seda.com ../../../WEB-INF/xsd/maf-actions.xsd">

	<global-ruleset>
 		<regexset>
 			<regex name="codice5char_regex">
 				<pattern>^\w{1,5}|\s{1,5}$</pattern>
 				<description></description>
 			</regex>
 			<regex name="codice12char_regex">
 				<pattern>^\w{1,12}|\s{1,12}$</pattern>
 				<description></description>
 			</regex>
 			<regex name="codice16char_regex">
 				<pattern>^\w{1,16}$</pattern>
 				<description></description>
 			</regex>
 			<regex name="codice20char_regex">
 				<pattern>^\w{1,20}$</pattern>
 				<description></description>
 			</regex>
 			<regex name="num15_regex">
 				<pattern>^\d{1,15}$</pattern>
 				<description>digits</description>
 			</regex>
 			<regex name="descrizione20_regex">
 				<pattern>^[\w\t \?+().,;'* \$ % @ = -]{0,20}$</pattern>
 				<description></description>
 			</regex>
 			<regex name="descrizione64_regex">
 				<pattern>^[\w\t \?+().,;'* \$ % @ = -]{0,64}$</pattern>
 				<description></description>
 			</regex>
 		</regexset>
 	</global-ruleset>

    <action url="riconciliazioneTransazioniNodo.do" screen="riconciliazioneTransazioniNodo.screen" flow="true">
        <action-class>org.seda.payer.manager.riconciliazionenn.actions.RiconciliazioneTransazioniNodoAction</action-class>
        <flow class="org.seda.payer.manager.riconciliazionenn.flows.RiconciliazioneTransazioniNodoFlow">
        	<result value="ricerca" screen="riconciliazioneTransazioniNodo.screen"/>
			<result value="stampa" writer="pdfMovimenti" content-type="application/pdf" inScope="false" attach="pdfMovimenti" />
        </flow>
          <ruleset>
			<rule name="codiceAbi" regex="codice5char_regex">
        		<missing severity="continue"/>
        		<malformed severity="fatal"/>
        	</rule>
			<rule name="codiceSia" regex="codice5char_regex">
        		<missing severity="continue"/>
        		<malformed severity="fatal"/>
        	</rule>
			<rule name="ccb" regex="codice12char_regex">
        		<missing severity="continue"/>
        		<malformed severity="fatal"/>
        	</rule>
			<rule name="nomeSupporto" regex="descrizione20_regex">
        		<missing severity="continue"/>
        		<malformed severity="fatal"/>
        	</rule>
           	<rule name="importo_da">
        		<validation>numberIT;maxlength=15</validation>
        		<missing severity="continue"/>
        		<malformed severity="fatal"/>
        	</rule>  
        	<rule name="importo_a">
        		<validation>numberIT;maxlength=15</validation>
        		<missing severity="continue"/>
        		<malformed severity="fatal"/>
        	</rule>  	
        </ruleset> 	
        		
    </action>

    <action url="riconciliazioneManualeTransazioniNodo.do" screen="riconciliazioneManualeTransazioniNodo.screen" flow="false">
        <action-class>org.seda.payer.manager.riconciliazionenn.actions.RiconciliazioneManualeTransazioniNodoAction</action-class>
		<ruleset>
        	<rule name="codiceTransazione" regex="descrizione64_regex">
        		<missing severity="continue"/>
        		<malformed severity="fatal"/>
        	</rule>  
			<rule name="codiceAbi" regex="codice5char_regex">
        		<missing severity="continue"/>
        		<malformed severity="fatal"/>
        	</rule>
			<rule name="codiceSia" regex="codice5char_regex">
        		<missing severity="continue"/>
        		<malformed severity="fatal"/>
        	</rule>
			<rule name="ccb" regex="codice12char_regex">
        		<missing severity="continue"/>
        		<malformed severity="fatal"/>
        	</rule>
			<rule name="nomeSupporto" regex="descrizione20_regex">
        		<missing severity="continue"/>
        		<malformed severity="fatal"/>
        	</rule>
        </ruleset>
    </action>

	<action url="ritorna.do" flow="true">
		<description>Action per la gestione del ritorno ad altro screen con viewstate</description>
        <action-class>org.seda.payer.manager.riconciliazionenn.actions.RitornaAction</action-class>
        <flow class="org.seda.payer.manager.riconciliazionenn.flows.RitornaFlowManager">
           	<result value="riconciliazionemanualetransazioniNodo" screen="riconciliazioneManualeTransazioniNodo.do" />
           	<result value="riconciliazionetransazioninodo" screen="riconciliazioneTransazioniNodo.do" />
        </flow>
    </action>  
    
    <action url="associaTransazioneNodo.do" screen="riconciliazioneManualeTransazioniNodo.screen" flow="false">
        <action-class>org.seda.payer.manager.riconciliazionenn.actions.AssociaTransazioneNodoAction</action-class>
    </action>
    
    <action url="eliminaAssociazioneNodo.do" screen="riconciliazioneManualeTransazioniNodo.screen" flow="false">
        <action-class>org.seda.payer.manager.riconciliazionenn.actions.EliminaAssociazioneNodoAction</action-class>
    </action>

    <action url="forzaChiusuraQuadraturaNodo.do" screen="riconciliazioneTransazioniNodo.screen" flow="false">
        <action-class>org.seda.payer.manager.riconciliazionenn.actions.ForzaChiusuraQuadraturaNodoAction</action-class>
    </action>

    <action url="scaricaMovimento.do"  writer="true">
        <action-class>org.seda.payer.manager.riconciliazionenn.actions.ScaricaMovimentoAction</action-class>
		<writer id="flussoCBI" content-type="plain/txt" inScope="false" attach="flussoCBID"/>
    </action>

    <action url="dettaglioTransazioneNodo.do" screen="dettaglioTransazioneNodo.screen" flow="false">
        <action-class>org.seda.payer.manager.riconciliazionenn.actions.DettaglioTransazioneNodoAction</action-class>
    </action>
    
	<action url="reinvioFlussoQuadraturaNodo.do" screen="riconciliazioneTransazioniNodo.screen" flow="true">
		<action-class>org.seda.payer.manager.riconciliazionenn.actions.ReinvioFlussoQuadraturaAction</action-class>
		<flow class="org.seda.payer.manager.riconciliazionenn.flows.RiconciliazioneTransazioniNodoFlow">
			<result value="ricerca" screen="riconciliazioneTransazioniNodo.do"/>
		</flow>
	</action>
	<!--  inizio LP PG200200 -->
    <action url="dettaglioIUVFlusso.do" screen="dettaglioIUVFlusso.screen" flow="false">
        <action-class>org.seda.payer.manager.riconciliazionenn.actions.DettaglioIUVFlussoAction</action-class>
    </action>
    
    <action url="ritentaQuadraturaFlusso.do" flow="true">
        <action-class>org.seda.payer.manager.riconciliazionenn.actions.RitentaQuadraturaFlussoAction</action-class>
        <flow class="org.seda.payer.manager.riconciliazionenn.flows.RiconciliazioneTransazioniNodoFlow">
        	<result value="ricerca" screen="riconciliazioneTransazioniNodo.do"/>
        </flow>
    </action>
	<!--  fine LP PG200200 -->
</actions-mapping>

=== regione-marche/org.seda.payer.manager.web/WebContent/applications/payer/wismanager/maf-actions.xml
<?xml version="1.0" encoding="UTF-8"?>

<actions-mapping xmlns="http://action.core.maf.j2ee5.seda.com"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://action.core.maf.j2ee5.seda.com ../../../WEB-INF/xsd/maf-actions.xsd">
	
	   
    <action url="wismanager.do" flow="true">
		<role-collection>
			<role>AMMI</role>
			<role>AMSO</role>
			<role>AMUT</role>
			<role>AMEN</role>
		</role-collection>
        <action-class>org.seda.payer.manager.wismanager.actions.WisManager</action-class>
        <flow class="org.seda.payer.manager.flows.DispatchFlow">
			<result value="search" screen="wismanager.screen"/>
			<result value="cambiaProvincia" screen="wismanager.screen"/>
			<result value="avantiWIS" redirect="urlRedirectWIS"/>
		</flow>
					
    </action>
    
    
</actions-mapping>

=== regione-marche/org.seda.payer.manager.web/WebContent/applications/payer/inviaUfficio/maf-actions.xml
<?xml version="1.0" encoding="UTF-8"?>

<actions-mapping xmlns="http://action.core.maf.j2ee5.seda.com"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://action.core.maf.j2ee5.seda.com ../../../WEB-INF/xsd/maf-actions.xsd">

	<action url="inviaufficio.do" screen="inviaufficio.screen" flow="true">
		<role-collection>
			<role>AMMI</role>
			<role>AMSO</role>
			<role>AMUT</role>
			<role>AMEN</role>
		</role-collection>
		<action-class>org.seda.payer.manager.inviaUfficio.actions.InviaUfficioAction</action-class>
		<flow class="org.seda.payer.manager.configurazione.actions.ConfigurazioneFlowAction">
			<result value="add" screen="inviaufficioactionadd.do" />
			<result value="ritorna" screen="inviaufficio.screen" />
			<result value="search" screen="inviaufficio.screen" />
			<result value="delete" screen="inviaUfficio_delete.screen" />
		</flow>
    </action>

	<action url="inviaufficioactionadd.do" screen="inviaufficioactionadd.screen" flow="true">
		<role-collection>
			<role>AMMI</role>
			<role>AMSO</role>
			<role>AMUT</role>
			<role>AMEN</role>
		</role-collection>
		<action-class>org.seda.payer.manager.inviaUfficio.actions.InviaUfficioActionAdd</action-class>
		<flow class="org.seda.payer.manager.configurazione.actions.ConfigurazioneFlowAction">
			<result value="add" screen="inviaufficioactionadd.screen" />
			<result value="ritorna" screen="inviaufficio.do" />
			<result value="init" screen="inviaufficioactionadd.screen" />
		</flow>
	</action>

</actions-mapping>

=== regione-marche/org.seda.payer.manager.web/WebContent/applications/payer/monitoraggionn/maf-actions.xml
<?xml version="1.0" encoding="UTF-8"?>

<actions-mapping xmlns="http://action.core.maf.j2ee5.seda.com"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://action.core.maf.j2ee5.seda.com ../../../WEB-INF/xsd/maf-actions.xsd">
	
	<global-ruleset>
 		<regexset>
 			<regex name="descrizione64_regex">
 				<pattern>^(?:(?!').)*{0,64}$</pattern>
 				<description></description>
 			</regex>
 		</regexset>
 	</global-ruleset>
    
    <action url="monitoraggionn.do" screen="monitoraggionn.screen">
        <action-class>org.seda.payer.manager.monitoraggionn.actions.MonitoraggioNnAction</action-class>
		<ruleset>
        	<rule name="txtIdTransazione" regex="descrizione64_regex">
        		<missing severity="continue"/>
        		<malformed severity="fatal"/>
        	</rule>  
        	<rule name="txtNumeroDocumento">
        		<validation>maxlength=128</validation>
        		<missing severity="continue"/>
        		<malformed severity="fatal"/>
        	</rule>  
        	<rule name="txtNumeroOperazione">
        		<validation>maxlength=128</validation>
        		<missing severity="continue"/>
        		<malformed severity="fatal"/>
        	</rule>  
        </ruleset> 
    </action>
    
    <action url="downloadXml.do" writer="true">
    	<action-class>org.seda.payer.manager.monitoraggionn.actions.DownloadXmlAction</action-class>
    	<writer id="file_xml" content-type="plain/txt" inScope="true" attach="nome_file_xml"/>
    </action>

	<action url="dettaglioNodo.do" screen="monitoraggionndettaglio.screen">
		<action-class>org.seda.payer.manager.monitoraggionn.actions.MonitoraggioNnDettaglioAction</action-class>
	</action>
	
	<action url="ritorna.do" screen="monitoraggionn.do">
		<description>Action per la gestione del ritorno ad altro screen con viewstate</description>
        <action-class>org.seda.payer.manager.monitoraggionn.actions.RitornaAction</action-class>
    </action>  
    
    <action url="notifica.do" flow="true">
        <action-class>org.seda.payer.manager.monitoraggionn.actions.NotificaAction</action-class>
        <flow class="org.seda.payer.manager.monitoraggionn.flows.MonitoraggioNnNodoFlow">
        	<result value="monitoraggionn" screen="monitoraggionn.screen"/>
        	<result value="monitoraggionndettaglio" screen="monitoraggionndettaglio.screen"/>
        </flow>
    </action> 

</actions-mapping>

=== regione-marche/org.seda.payer.manager.web/WebContent/applications/payer/modello3config/maf-actions.xml
<?xml version="1.0" encoding="UTF-8"?>

<actions-mapping xmlns="http://action.core.maf.j2ee5.seda.com"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://action.core.maf.j2ee5.seda.com ../../../WEB-INF/xsd/maf-actions.xsd">
	
		<global-ruleset>
 		<regexset>
 			<regex name="descrizione_regex">
 				<pattern>^[a-zA-Z]+(([\'\,\.\- ][a-zA-Z ])?[a-zA-Z]*)*{1,256}$</pattern>
 				<description></description>
 			</regex>
 			<regex name="codice3char_regex">
 				<pattern>^\w{1,3}$</pattern>
 				<description></description>
 			</regex>
 			<regex name="date_yyyy_mm_dd_regex">
 				<pattern>^(19|20)\d\d([-])(0[1-9]|1[012])([-])(0[1-9]|[12][0-9]|3[01])$</pattern>
 				<description></description>
 			</regex>
 			<regex name="codice20char_regex">
 				<pattern>^\w{1,20}$</pattern>
 				<description></description>
 			</regex>
 			<regex name="codicefisc_regex">
 				<pattern>^[a-zA-Z]+(([\'\,\.\- ][a-zA-Z ])?[a-zA-Z]*)*{1,16}$</pattern>
 				<description></description>
 			</regex>
 			
 		</regexset>
 	</global-ruleset>
			
    <action url="modello3.do" screen="modello3.screen" flow="true">
		<role-collection>
			<role>AMMI</role>
			<role>AMSO</role>
			<role>AMUT</role>
			<role>AMEN</role>
		</role-collection>
        <action-class>org.seda.payer.manager.modello3config.actions.Modello3Action</action-class>
        <flow class="org.seda.payer.manager.modello3config.flows.Modello3FlowAction">
           	<result value="Search" screen="modello3.screen" />
           	<result value="DownloadCsv" screen="modello3Csv.do" />
           	<result value="add" screen="modello3Edit.do?codop=add" />
        </flow>
         <ruleset>
        	<rule name="pageNumber" regex="num8_regex">
        		<missing severity="continue"/>
        		<malformed severity="continue"><rule-action class="com.seda.j2ee5.maf.defender.action.impl.Blank"/></malformed>
        	</rule>
        	<rule name="rowsPerPage" regex="num3_regex">
        		<missing severity="continue"/>
        		<malformed severity="continue"><rule-action class="com.seda.j2ee5.maf.defender.action.impl.Blank"/></malformed>
        	</rule>
        	
        	<rule name="tx_societa" regex="codice5obblchar_regex">
        		<missing severity="continue"/>
        		<malformed severity="continue"><rule-action class="com.seda.j2ee5.maf.defender.action.impl.Blank"/></malformed>
        	</rule>
			<rule name="tx_utente" regex="codice5obblchar_regex">
        		<missing severity="continue"/>
        		<malformed severity="continue"><rule-action class="com.seda.j2ee5.maf.defender.action.impl.Blank"/></malformed>
        	</rule>
			<rule name="tx_provincia" regex="codice2obblchar_regex"> 
        		<missing severity="continue"/>
        		<malformed severity="continue"><rule-action class="com.seda.j2ee5.maf.defender.action.impl.Blank"/></malformed>
        	</rule>
			<rule name="tx_ente" regex="codice10obblchar_regex">
        		<missing severity="continue"/>
        		<malformed severity="continue"><rule-action class="com.seda.j2ee5.maf.defender.action.impl.Blank"/></malformed>
        	</rule>
			
        </ruleset> 			
    </action>
    <action url="modello3Edit.do" screen="modello3Edit.screen" flow="true">
		<role-collection>
			<role>AMMI</role>
			<role>AMSO</role>
			<role>AMUT</role>
			<role>AMEN</role>
		</role-collection>
        <action-class>org.seda.payer.manager.modello3config.actions.Modello3EditAction</action-class>
        <flow class="org.seda.payer.manager.modello3config.flows.Modello3EditFlowAction">
           	<result value="Search" screen="modello3Edit.screen" />
           	<result value="edit" screen="modello3.do" />
           	<result value="DownloadCsv" screen="downloadListaCsv.do" />
           	<result value="cancella" screen="modello3Cancel.screen" />
           	<result value="ritorna" screen="ritorna.do" />
        </flow>
         <ruleset>
        	<rule name="pageNumber" regex="num8_regex">
        		<missing severity="continue"/>
        		<malformed severity="continue"><rule-action class="com.seda.j2ee5.maf.defender.action.impl.Blank"/></malformed>
        	</rule>
        	<rule name="rowsPerPage" regex="num3_regex">
        		<missing severity="continue"/>
        		<malformed severity="continue"><rule-action class="com.seda.j2ee5.maf.defender.action.impl.Blank"/></malformed>
        	</rule>
        	
        	<rule name="tx_societa" regex="codice5obblchar_regex">
        		<missing severity="continue"/>
        		<malformed severity="continue"><rule-action class="com.seda.j2ee5.maf.defender.action.impl.Blank"/></malformed>
        	</rule>
			<rule name="tx_utente" regex="codice5obblchar_regex">
        		<missing severity="continue"/>
        		<malformed severity="continue"><rule-action class="com.seda.j2ee5.maf.defender.action.impl.Blank"/></malformed>
        	</rule>
			<rule name="tx_provincia" regex="codice2obblchar_regex"> 
        		<missing severity="continue"/>
        		<malformed severity="continue"><rule-action class="com.seda.j2ee5.maf.defender.action.impl.Blank"/></malformed>
        	</rule>
			<rule name="tx_ente" regex="codice10obblchar_regex">
        		<missing severity="continue"/>
        		<malformed severity="continue"><rule-action class="com.seda.j2ee5.maf.defender.action.impl.Blank"/></malformed>
        	</rule>
			
        </ruleset> 			
    </action>
     	
    
    <action url="ritorna.do" flow="true">
		<role-collection>
			<role>AMMI</role>
			<role>AMSO</role>
			<role>AMUT</role>
			<role>AMEN</role>
	    </role-collection>
		<description>Action per la gestione del ritorno ad altro screen con viewstate</description>
        <action-class>org.seda.payer.manager.modello3config.actions.RitornaAction</action-class>
        <flow class="org.seda.payer.manager.modello3config.flows.RitornaFlowAction">
	        <result value="modello3" screen="modello3.do" /> 
        </flow>
    </action> 
    
</actions-mapping>
